### ISSUE TITLE
[fix] ComboBox Default value, and no result found issue

### ISSUE THREAD

**Issue by m-bilal-dev9** [trussworks/react-uswds#1083]
**ReactUSWDS Version & USWDS Version:**

- react-uswds: 1.14
- uswds: 2.9

**Describe the bug**

Default value option not working, and on first open it shows no results message but by default it should show all options.
Moreover on change event is returning undefined on first render.

**To Reproduce**

1. Create the ComboBox with below code
2. Provide the default value
3. Console.log the onChange event value (You'll see undefined and empty input value of ComboBox)

```
 <ComboBox
        name="countryId"
        id="countryId"
        options={countries.map((country: Country) => ({
          label: country.name,
          value: country.id
        }))}
        onChange={(val: string) => onChange('countryId', val)}
        defaultValue={values.countryId}
      ></ComboBox>
```
**Expected behavior**
It should initialise the ComBox with provided default value as it exists in options and by default it should show all options instead of no result found message.

**Screenshots**
Here is small video of issue:

https://user-images.githubusercontent.com/77671366/113198049-e296cb80-927e-11eb-81c4-06cda8e45e63.mov

**Additional context**

- Using typescript

**Comment by brandonlenz** [comment]
Hi @m-bilal-dev9! Thanks for reporting an issue.

Would you be able to provide the value that is being passed in to the defaultValue prop (`values.countryId` from `defaultValue={values.countryId}`)? This is working in our storybook example at https://trussworks.github.io/react-uswds/?path=/docs/components-form-controls-combo-box--with-default-value so I'm wondering if something unexpected is happening with the value passed in.

**Comment by m-bilal-dev9** [comment]
**Countries list:**

- **value:** 42368415-7f6f-40aa-80bf-543dcd6e95ac **label:** British Indian Ocean Territory
- **value:** c1fe0261-6d60-4164-8533-7e8992a4a77c **label:** Bangladesh

**DefaultValue:** c1fe0261-6d60-4164-8533-7e8992a4a77c

Yes, I tried to implement from your storybook but it's not working.

**Comment by m-bilal-dev9** [comment]
@brandonlenz Thanks for help, I've found the issue.
Actually, I'm loading countries list from database using useEffect hook that's why during first render default value get set to undefined.

So, I've fixed this:
```
{countries.length > 0 && (<ComboBox
        name="countryId"
        id="countryId"
        options={countries.map((country: Country) => ({
          label: country.name,
          value: country.id
        }))}
        onChange={(val: string) => onChange('countryId', val)}
        defaultValue={values.countryId}
      ></ComboBox>)}
```
How can I reset the combobox value to empty string | null without clicking the 'x' icon. As my country field is dependent on regions field so on region change I reload countries list and want to clear the selected option of previous country region.
Temporarily, I'm using this:
// temporary fix to reset combobox box
`document.querySelectorAll('.usa-combo-box__clear-input').forEach((el) => (el instanceof HTMLElement ? el.click() : el));`

**Comment by brandonlenz** [comment]
@m-bilal-dev9 if you update the `defaultValue` to `undefined` whenever your region field changes you can achieve this effect.

I could see that being done via useState for the selected countryId for example, which you may already be doing.

Does that work for you?

**Comment by m-bilal-dev9** [comment]
@brandonlenz I've already tried the solution which you are suggesting but it didn't work. After setting defaultValue to undefined it still shows country label in the input field.

**Comment by brandonlenz** [comment]
@m-bilal-dev9 I think this would be worthwhile enhancement to add a simple way to programmatically clear a ComboBox. Would you mind opening a feature request issue for that? 

I will close this issue since the reported behavior has been resolved.
