### ISSUE TITLE
Abiliity to import the StepIndicator and StepIndicatorStep components

### ISSUE THREAD

**Issue by alexFranka** [trussworks/react-uswds#1131]
**ReactUSWDS Version & USWDS Version:**

@trussworks/react-uswds => 1.14.0
uswds =>2.11.1

**Describe the bug**

Trying to import the components to implement the Stepper yields an error

**To Reproduce**

1. adding `import { StepIndicator, StepIndicatorStep } from '@trussworks/react-uswds';` to the top of any React component file (tsx)
2. Yields an error in the browser `Module not found: Can't resolve '@trussworks/react-uswds/lib/components/stepindicator/StepIndicatorStep/StepIndicatorStep'`

**Expected behavior**

Importing a component from `@trussworks/react-uswds` should render w/o errors

**Screenshots**

![Screen Shot 2021-04-12 at 7 29 30 AM](https://user-images.githubusercontent.com/4030056/114394624-06042500-9b61-11eb-90b6-da4dd5e6109f.png)
![Screen Shot 2021-04-12 at 7 30 13 AM](https://user-images.githubusercontent.com/4030056/114394649-0d2b3300-9b61-11eb-917e-ceccf649be03.png)
<img width="1076" alt="Screen Shot 2021-04-12 at 7 29 55 AM" src="https://user-images.githubusercontent.com/4030056/114394660-11efe700-9b61-11eb-903a-6554efe37e4e.png">

**Additional context**
Using typescript
`index.d.ts `has no exported members related to the stepIndicator components

**Device and Browser Information (please complete the following information if describing a UI bug):**

MacOS
Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Comment by alexFranka** [comment]
Using typescript

**Comment by suzubara** [comment]
Hi @alexFranka ! The StepIndicator components haven't been merged into a release of the library yet so I'm closing this issue. It should be included in our next release (most likely 1.15.0).

**Comment by alexFranka** [comment]
Thanks!
