### ISSUE TITLE
[feat] Add a simple way to programmatically clear a ComboBox

### ISSUE THREAD

**Issue by m-bilal-dev9** [trussworks/react-uswds#1137]
**Does your feature request relate to a specific USWDS component?**
Related to ComboBox.

**What USWDS Version is this feature present in?**
react-uswds: 1.10

**Is your feature request related to a problem? Please describe.**
Unable to reset the ComboBox value.

**Describe the solution you'd like**
Add a simple way to programmatically clear a ComboBox

**Describe alternatives you've considered**
// temporary fix to reset combobox box
`document.querySelectorAll('.usa-combo-box__clear-input').forEach((el) => (el instanceof HTMLElement ? el.click() : el));`

**Comment by haworku** [comment]
This work was completed
