### ISSUE TITLE
[deps] update testing-library version

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#1161]
**Describe the bug**

Dependabot is unable to manually update this dependency as it requires code changes to be made.
E.g. https://github.com/trussworks/react-uswds/pull/1146

**Expected behavior**

Manually updating the dependency and fixing broken tests/build steps should allow dependabot to once again automatically perform minor updates.

**Additional context**

See failing build log for https://github.com/trussworks/react-uswds/pull/1146

**Comment by brandonlenz** [comment]
Opened #1193 referencing this issue, but closing this issue since the actual problem that spawned this issue has been resolved.

**Comment by ahobson** [comment]
dependably PRs #1350 and #1351 were closed because of test run failures

**Comment by brandonlenz** [comment]
Looks like @suzubara fixed what @ahobson linked in https://github.com/trussworks/react-uswds/pull/1546/commits. Nice!!
