### ISSUE TITLE
[feat] SiteAlert children enhancement

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#1191]
**Does your feature request relate to a specific USWDS component?**

Site Alert (2.10.x)

Currently SiteAlert requires children to be manually built and passed in. This means we are not encapsulating the (optional) `usa-alert__text` sub component.

**Describe the solution you'd like**

See the following thread for enhancement to SiteAlert (and Alert): https://github.com/trussworks/react-uswds/pull/1099#discussion_r609744998

Modifying `children` to allow `string | React.ReactElement | React.ReactElement[]` would allow us to render `string` inside the `usa-alert__text` internally, otherwise just render `children` directly.

A further enhancement would be the creation of the `AlertText` subcomponent which would allow encapsulation of the `usa-alert__text` class within a `p` tag based component, and also allow rich text via things like `<strong>` to be passed in (which would not be possible passing just a `string` as in the first enhancement).

**Describe alternatives you've considered**

There are a couple of options in the thread. Use discretion around preserving backwards compatibility, and how much time is available to

**Comment by kylehilltruss** [comment]
What do folks think is the best location for a `AlertText` sub-component? This can certainly go alongside the `SiteAlert` component (since it's not a top-level part of the WDS in and of itself), but the same functionality can used in a similar way in the `Alert` component as well.

Right now, the Alert component is [tightly coupled](https://github.com/trussworks/react-uswds/blob/main/src/components/Alert/Alert.tsx#L47-L51) to _sometimes_ adding in the `usa-alert__text` class, but that could change if we wanted it to (though I'd worry about introducing a breaking change there).

**Comment by brandonlenz** [comment]
> What do folks think is the best location for a AlertText sub-component? This can certainly go alongside the SiteAlert component (since it's not a top-level part of the WDS in and of itself), but the same functionality can used in a similar way in the Alert component as well.

> Right now, the Alert component is tightly coupled to sometimes adding in the usa-alert__text class, but that could change if we wanted it to (though I'd worry about introducing a breaking change there).

@kylehilltruss sorry I missed your question here from a few weeks ago.

It's a good question. I'm not aware of two separate, top-level components making use of the same sub-component in our codebase at the moment. I could see us doing something like putting `SiteAlert`, `Alert`, and `AlertText` in an `alert` directory within the project.

Based on https://trussworks.slack.com/archives/C0122MPMXL3/p1622054137029800 in slack, @christopherhuii is potentially taking a look at this too and may have some input on the refactor of `Alert`
