### ISSUE TITLE
[feat] New Component: Input prefix or suffix

### ISSUE THREAD

**Issue by SirenaBorracha** [trussworks/react-uswds#1235]
# [Input prefix or suffix](https://designsystem.digital.gov/components/input-prefix-suffix/)

## USWDS Version

[2.11.0](https://github.com/uswds/uswds/releases/tag/v2.11.0)

## Description

Use input prefixes and suffixes to show symbols or abbreviations that help users enter the right type of information in a form’s text input.

## Requirements (proposed)

**Prop Interface**

```JSX
interface InputPrefixSuffixProps = {
 type: ‘prefix’ | ‘suffix’
 className?: string
 children: React.ReactNode
} & JSX.IntrinsicElements['div']
```

## Example Implementation (proposed)

```JSX
return (
  <FormGroup>
    <label class="usa-label" for="example-input-prefix">Credit card number</label>
    <InputPrefixSuffix type="prefix">
      <Icon name="credit_card"/>
    </InputPrefixSuffix>
  </FormGroup>

  <FormGroup error={true}>
    <label class="usa-label" for="example-input-prefix-error">Credit card number (Error)</label>
    <InputPrefixSuffix type="prefix">
      <Icon name="credit_card"/>
    </InputPrefixSuffix>
  </FormGroup>

   <FormGroup>
     <label class="usa-label" for="example-input-suffix">Weight, in pounds</label>
    <InputPrefixSuffix type="suffix">
      lbs.
    </InputPrefixSuffix> 
  </FormGroup>
)
```

**More Details**

- `<div>`root element

## Other Considerations

-

**Comment by jenbutongit** [comment]
👋 Hey there, I'm an engineer currently consulting in uk gov, are you still looking for contributors for this? Happy to look into it 🤓

@SirenaBorracha - I think for your proposed prop interface you meant to use `type` instead of `interface`. Using interface  with `& JSX.xx` will give you this namespace error TS2708: Cannot use namespace 'JSX' as a value.

I'd also suggest two components here, but happy to concede (since we don't have this component ourselves so I'm not sure how your developers would rather use this component), I'd have one component for `InputPrefix` and one for `InputSuffix`, and remove the need for `type: ‘prefix’ | ‘suffix’`

Is InputPrefix|Suffix only applicable to textInputs? Could I suggest an API similar to this? https://github.com/NHSDigital/nhsuk-react-components/tree/main/src/components/error-summary

so in this case the implementation would be 
```tsx
 <FormGroup>
    <label class="usa-label" for="example-input-prefix">Credit card number</label>
    <TextInput.Prefix>
      <Icon name="credit_card"/>
    </TextInput.Prefix>
    <TextInput/>
  </FormGroup>
```

**Comment by brandonlenz** [comment]
Oh, and regarding 

> I think for your proposed prop interface you meant to use type instead of interface. Using interface with & JSX.xx will give you this namespace error TS2708: Cannot use namespace 'JSX' as a value.

The interface guidance we show often technically does not "compile", but serves as a somewhat convenient shorthand for Github issues. Definitely can see why that would be confusing. 

You should be able to use an interface for the props and append the & JSX.IntrinsicElements[] to the props in the component's function signature. You'll likely notice that's how most components in the library are structured, e.g. Button:

```TSX
export const Button = ({
  type,
  children,
  secondary,
  base,
  accent,
  accentStyle,
  outline,
  inverse,
  size,
  big,
  small,
  icon,
  unstyled,
  onClick,
  className,
  ...defaultProps
}: ButtonProps & JSX.IntrinsicElements['button']): React.ReactElement => {
  ...
}
```

**Comment by jenbutongit** [comment]
👋 Hey @brandonlenz - I'm all finished up, I've forked the repo and worked on a branch following your branch convention [jenbutongit-new-component-InputPrefixSuffix-1235](https://github.com/jenbutongit/react-uswds/tree/jenbutongit-new-component-InputPrefixSuffix-1235).

Does this comment still stand? 
>Note: Currently our CI cannot run directly on external PRs (work from outside the Truss organization) and prevents merge. To manage this, we pull these PRs into a separate branch that a CODEOWNER creates, run automation, and merge from there. Your initial PR will be closed with a comment and your work will be merged instead from the related PR.
Do you mind opening up a branch (or finding a colleague to) so I can open my PR against, if I've read that correctly? 

In any case, test and linting has passed except for a lint warning that was existing on `ComboBox/utils`. 

I've followed/made a best guess of your component conventions as well. 

```
InputPrefixSuffix
├── InputPrefix.stories.tsx
├── InputPrefix.test.tsx
├── InputPrefix.tsx
├── InputSuffix.stories.tsx
├── InputSuffix.test.tsx 
├── InputSuffix.tsx
└── types.ts // the shared prop type for InputPrefix|Suffix
```

This might be a little bloated for the size of the components so let me know if you'd rather them consolidated into something like this

```
InputPrefixSuffix
├── InputPrefixSuffix.stories.tsx 
├── InputPrefixSuffix.test.tsx 
└── InputPrefixSuffix.tsx // exports { InputPrefix, InputSuffix } 
```

**Comment by brandonlenz** [comment]
@jenbutongit I see. 

I've pushed your branch up to an internal branch (https://github.com/trussworks/react-uswds/compare/main...jenbutongit-new-component-InputPrefixSuffix-1235). Are you able to open that PR, and would it count for you? Would you be able to push changes to that branch if there was code review requested?

If not, then your approach is likely the better one. Let me know :smile:

**Comment by brandonlenz** [comment]
Yea, figures. Thanks for indulging me 😅 

Let's go with the approach you suggested! I've created the following branch as a landing zone for your forked branch: https://github.com/trussworks/react-uswds/tree/landing-jenbutongit-new-component-InputPrefixSuffix-1235

Open up a PR there and we'll use that to get your code merged in 😄
