### ISSUE TITLE
[feat] Unify icon usage

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#1303]
**Does your feature request relate to a specific USWDS component?**

Dependent on new react-uswds Icon component. PR: https://github.com/trussworks/react-uswds/pull/1241
More context: https://github.com/trussworks/react-uswds/issues/992

**What USWDS Version is this feature present in?**
USWDS 2.11 +

**Is your feature request related to a problem? Please describe.**
USWDS has moved away from Font Awesome towards Google Material Icons, as well as using SVG icon sprite. Some of the changes are discussed in this [video](https://youtu.be/OhtiTfKAIRw?t=2843). We will follow suit and update this codebase as we move to 2.11. This will require making some documentation edits as well as using our new [Icon ](https://designsystem.digital.gov/components/icon/) component.

**Describe the solution you'd like**
Several steps to take here:
- [x] [Make sure react-uswds is on 2.11+](https://github.com/trussworks/react-uswds/issues/1304)
- [ ] Double check our components are using the correct uswds icons. `GovBanner` uses a lock icon for example.
- [ ] Replace usage of icons in our components with our react-uswds `<Icon>`. 
- [x] In our styles and assets documentation we're recommend use fontawesome per uswds' previous recommendation. Our documentation needs to be updated here to remove reference to fontawesome in favor of Material icons.
- [x] Remove usage of @fortawesome fontawesome in example app entirely
- [ ] USWDS examples set some intrinsic props on `<svg/>` tags to defaults (e.g. focusable and role). We should set the same defaults in our code,  but allow override these html attributes if the corresponding prop is passed to the Icon component

**Comment by werdnanoslen** [comment]
>  USWDS examples set some intrinsic props on <svg/> tags to defaults (e.g. focusable and role). We should set the same defaults in our code, but allow override these html attributes if the corresponding prop is passed to the Icon component

I'm following up on this point in https://github.com/uswds/uswds/issues/4307#issuecomment-1559795212.
