### ISSUE TITLE
[chore] Upgrade to typescript 4.9.x

### ISSUE THREAD

**Issue by ahobson** [trussworks/react-uswds#1383]
The PR #1380 shows the failing build

**Comment by brandonlenz** [comment]
It looks like the failures are related to the type script loader we use. It not longer works with newer typescript versions. Unfortunately, it also has not been updated in 3 years 😬 

For reference: https://www.npmtrends.com/awesome-typescript-loader-vs-ts-loader

I'm looking in to swapping over to ts-loader, but it doesn't like some of our TS declarations for function overloading around `Link`

**Comment by rpdelaney** [comment]
See #2253

**Comment by haworku** [comment]
Closing in favor of #2213
