### ISSUE TITLE
GH Workflow: Publish to "next" on every merge to develop

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#147]
Create a Github workflow that:
- Every time a PR is merged to develop, publish to the `next` tag on npm (if tests pass)

This will require storing an npm token in GH. Probably a job for @trussworks-infra

**Comment by suzubara** [comment]
After discussing with @trussworks-infra we've come to a slightly different strategy...

**The problem:**
- We currently require 2FA auth in order to publish this package to npm
- NPM does not have any way to circumvent 2FA for automated publishing (they suggest using a CIDR-restricted token which is not a realistic option for us)
- The only way around this would be to remove 2FA and introduce token rotation policy to this project, which would probably incur more of a manual headache than the automated publishing is worth

**The proposed solution:**
- Publish the `next` tag to Github package registry instead of npm
- Pro: we don't need to set up npm auth tokens in order to publish via a Github action
- Con: installing & publishing to Github package registry requires some additional set up both for users and for us
- Caveat: someone who wants to use the `next` tag is already doing some extra lift, so hopefully that additional set up is not a blocker for them (and will deter just anyone from using `next`)
- Caveat: Github bought npmjs, so maybe in the future they'll be better integrated anyways

I still need to experiment with the actual publishing workflow, but wanted to run the above by everyone first. This is definitely not an ideal solution, but it feels like the best option for right now. please comment if you have any concerns!

**Comment by haworku** [comment]
Capturing conversation from Slack here.

@suzubara uncovered that publishing on Github’s registry doesn’t explicitly support different release streams at this time. There is a un/underdocumented way to get it to work but we decided to wait until GH package repo is more mature (and things are officially documented) to implement.
