### ISSUE TITLE
[refactor] Tooltip enhancements

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#1541]
**Does your feature request relate to a specific USWDS component?**
[Tooltip](https://designsystem.digital.gov/components/tooltip/)

**What USWDS Version is this feature present in?**
2.11.0

**Is your feature request related to a problem? Please describe.**
Follow on task from discussion in #1027

**Comment by werdnanoslen** [comment]
@haworku can you say more about the enhancements expected here? The Suggested changes from #1027 are all implemented
