### ISSUE TITLE
[feat] Navigation scrollbar enhancement

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#1620]
**Does your feature request relate to a specific USWDS component?**

USWDS [2.11.0](https://github.com/uswds/uswds/releases) made an adjustment to the [mobile navigation toggle behavior](https://github.com/uswds/uswds/commit/e06173bd4be19d48acf0169800a1305858e35601#diff-8a64a8fab0087c66da90fa17268ef296d8d53ad9987bb61da043f802f4771280) that we should replicate in our implementation if appropriate. It appears to modify the `body` padding to account for the scrollbar width when opening/closing the nav.

**What USWDS Version is this feature present in?**

2.11.0

**Comment by werdnanoslen** [comment]
Strange, I'm not sure what this used to do, but in all browsers for both our and USWDS's implementations it seems to just set the padding to zero in a complicated way. I wonder if this is working correctly anymore even on their side, and even if it is, this is something implemented by the user (it'd just show up in our stories, not the component itself). Do y'all think this is worth pursuing or closing in favor of a future update from them on this function?
