### ISSUE TITLE
New component: Forms / Character count

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#169]
# [Character Count](https://designsystem.digital.gov/components/form-controls/#character-count)
Character count helps users know how much text they can enter when there is a limit on the number of characters.

## Proposed Requirements

```
Props = {
  id: string,
  name: string
  maxLength: number
  defaultValue?: string
  isTextArea?: boolean
  getCharacterCount?: (text: string) => number
  getCharacterCountMessage? : (remainingCount: number) => string
  inputRef: InputRef
} 
```
- Supports both <`input type="text" />` and `<textarea>`
- Character limit is determined by the `maxLength`.  It does not limit the actual input field length, allowing the user to exceed the soft cap.
- Input is invalid when `maxLength` is exceeded
- `getCharacterCount` prop allows custom logic for character count (that accounts for emojis, ligatures, etc).  It defaults to a function that uses `.length`
- `getMessage` returns custom hint messages to display. It defaults to a function that returns English messages.
- Component state tracks the input text length and validity. The consumer can pass in props that calculate the character count and determine which messages to display.

## Other Considerations
- Account for no-JavaScript environments. Add a default message in the message element that refers to the character limit. This will appear in instances when JavaScript does not load. 
- Instead of using `<Label />` inside this component use [render props](https://reactjs.org/docs/render-props.html) as per https://github.com/trussworks/react-uswds/pull/217#pullrequestreview-423722119

**Comment by duncan-truss** [comment]
### Requirements

**Input types:**

- Supports both `<input type="text" />` and `<textarea>`

**Character limit:**

- Determined by the `maxlength` attribute on the input element.
- Does not limit the actual input field length, allowing the user to exceed the soft cap.

**Placeholder text states:**

No input: {maxlength} characters allowed
Input less than max plural/no characters left: {input length} characters left
Input less than max singular: 1 character left
Input over the max singular: 1 character over the limit
Input over the max plural: {input length - max} characters over limit

**Event Listeners:**

onChange: updates the hint element outside of the form group with the new placeholder template.  Adds invalid class when exceeding the max.

onBlur: if over the limit input field border gets red highlight

**Accessibility:**

- Need to match the `aria-describedby` with the label and character count message ids.
- Screen readers will announce when using the `arai-live="polite"` attribute on the character count message

### React Implementation

TBD
