### ISSUE TITLE
[ci] Build the library package in CI instead of on local machines

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#1725]
We've been tripped up a couple times now when publishing a new version by building the library on local dev machines. For example, not having local packages up-to-date or including artifacts that shouldn't be a part of the build. We are blocked on being able to publish a package to NPM from CI since we require 2FA, however we should still be able to run the test & build workflow to generate the `.tar.gz` artifact used in a release.

Maybe we can add a Github CI job that creates & stores that artifact, and simplify our release workflow to publish that artifact ([npm docs](https://docs.npmjs.com/cli/v6/commands/npm-publish) say you can `npm publish` "A url or file path to a gzipped tar archive containing a single folder with a package.json file inside.")

**Comment by haworku** [comment]
When this work is complete please take a look at #924 and see if anything from that ticket is still relevant here.

**Comment by brandonlenz** [comment]
Also looking at https://github.com/marketplace/actions/npm-publish#github-action which I assume the auth token might allow us to bypass 2FA

**Comment by brandonlenz** [comment]
> Also looking at https://github.com/marketplace/actions/npm-publish#github-action which I assume the auth token might allow us to bypass 2FA

Just to document here: This is possible using automation tokens, but the headache required for managing a rotation policy for an automation token is not something we're wanting to take on at the moment, so indeed, the publish step to NPM will stay manual
