### ISSUE TITLE
[fix] ComboBox doesn't fire change events on input

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#1730]
**ReactUSWDS Version & USWDS Version:**

ReactUSWDS: 2.4.1
USWDS: 2.11.2 (or all)

**Describe the bug**

Changing the value of the ComboBox component does not fire the `onChange` event for the text input or the select element. If you look at the [USWDS source code](https://github.com/uswds/uswds/blob/v2.11.2/src/js/components/combo-box.js#L43) (look for the `changeElementValue` function) these events are fired when:
- mount if there is a selected option
- when an option is selected
- when the input is cleared or reset

**To Reproduce**

1. Add an input `onChange` handler prop to an instance of the ComboBox
2. This handler will be called when typing into the text input, but _not_ when an option is selected

**Expected behavior**

I would expect onChange events to be called consistently with the USWDS implementation

**Comment by werdnanoslen** [comment]
Can't reproduce the problem, as both methods are reachable:
* To set a handler on _type_, use its `inputProps` prop with an `onChange` prop
* To set a handler on _selection_, use its `onChange` prop


![Image](https://github.com/trussworks/react-uswds/assets/764090/73bcba36-e6bf-4d28-8a16-458e531b6a6e)

![Image](https://github.com/trussworks/react-uswds/assets/764090/d852106e-e506-4830-8265-8fe1ca1b464f)
