### ISSUE TITLE
Add documentation for Trussel on/off-boarding

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#185]
Since most of the time, Trussels who are working on this library actively will probably be on Reserve, they may need to be onboarded/offboarded relatively quickly and frequently. We may also often run into the situation where a Trussel is not able to complete work in progress if they end up joining a new client project on short notice. We should add some documentation that outlines what to do when you are onboarding & offboarding as an "active" contributor to this project.

**Comment by suzubara** [comment]
My initial thoughts:
- Include adding yourself as a contributor to the `package.json` file
- Include adding or removing yourself from `CODEOWNERS` as you prefer
- Include instructions for handing off or wrapping up in-progress stories

It seems realistic that even some engineers will continue to contribute to this while on client work, so we shouldn't assume only Reserve engineers will be contributing. It may also be the case that someone on Reserve spends some time on this, but then stops, or is splitting their time with other work. Maybe we can call this group "active contributors" and people can self-select in/out as they need?

**Comment by duncan-truss** [comment]
I noticed the [Github Pages Storybook](https://trussworks.github.io/react-uswds/) wasn't linked anywhere.  Maybe that could be added to the description or somewhere obvious in the Readme.

**Comment by duncan-truss** [comment]
There was an initial git push error I received that seemed related to using the develop branch instead of master as the default.  Switching to the master branch and back seemed to fix things.

![Screen Shot 2020-05-19 at 5 19 24 PM](https://user-images.githubusercontent.com/52669884/82379444-f03fbb80-99f4-11ea-8e68-51b4fc18d31a.png)

**Comment by duncan-truss** [comment]
It's possible that Trussels may not even know there is a Slack channel #react-uswds depending on how they encounter this.

**Comment by suzubara** [comment]
thanks @duncan-truss ! I'm going to start this and discussion can continue in the PR

**Comment by eamahanna** [comment]
I agree this should be for active contributors within truss. I think this also will tie into creating additional general how to contribute documentation.
