### ISSUE TITLE
Proposal: start using enums instead of booleans for prop variants

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#187]
We have several components such as `Header`, `Footer`,  `Button`, and maybe even aspects of `Grid`, with  boolean props that can conflict. 

For example, you should not have the `big` and `medium` prop applied to the same footer. Some of this should be on the developer to use our props ... properly 😝... AND we also could starting using variants as well when helpful. 

Instead of booleans we could move towards a single prop named something like `size` or `type` that accepts one of these types. The types would be enums. How do folks feel about this? Is this something we could start code reviewing for and document as practice? 

Proposed requirements to close this issue:
- Add a type variant to the `Button` component (keep the old way of doing these props too but add a deprecation warning - it can be removed fully in next major release ).
- Write out additional issues for other components with this problem.
- Add description of best practices with props to #73

**Comment by suzubara** [comment]
agreed this is the way to go!

**Comment by haworku** [comment]
For requirements,  lets make reword this ticket to be about adding the variant to the `Button` component to start.
