### ISSUE TITLE
[feat] Allow Accordion component to accept different heading levels

### ISSUE THREAD

**Issue by kimallen** [trussworks/react-uswds#1904]
**Does your feature request relate to a specific USWDS component?**

[Accordion](https://github.com/trussworks/react-uswds/blob/main/src/components/Accordion/Accordion.tsx)

**What USWDS Version is this feature present in?**

**Is your feature request related to a problem? Please describe.**

The heading level is fixed at `h4`.  In order to meet accessibility guidelines, we can't skip heading levels, so we need the flexibility to choose the heading level that makes sense in the context of where it is used.

**Describe the solution you'd like**

I'd like to add a prop `headlingLevel` for Accordion, with a default (h4? not sure what would be the best default) that would allow the options of h2, h3, h4, h5, h6

**Describe alternatives you've considered**

**Additional context**

I am using this currently on my project, and the heading level of these accordions will need to be an h2 or h3.

**Comment by brandonlenz** [comment]
> h4? not sure what would be the best default

I think `h4` should indeed be the default for backwards compatibility. Since today its an h4 and you don't get a choice, when folks update, we want to make sure that its still h4 for them to avoid a breaking change.

**Comment by brandonlenz** [comment]
Adding a link to https://github.com/trussworks/react-uswds/pull/1865/files here since it is a great, recent example of how to achieve this
