### ISSUE TITLE
[fix] react-uswds storybook should work with Storybook Composition 

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#1912]
**ReactUSWDS Version & USWDS Version:**
2.11.12

**Describe the bug**

Try to add react-uswds to an existing storybook through  [storybook composition](https://storybook.js.org/docs/react/sharing/storybook-composition) and react uswds storybook does not load. The network request for the `stories.json` file returns 400

**Expected behavior**
You can add react-uswds storybook to another deployed storybook. 

**Screenshots**
<img width="411" alt="Screen Shot 2022-02-25 at 3 41 09 PM" src="https://user-images.githubusercontent.com/10750442/155806891-48b176e4-0d77-43b6-8bea-1e8c90df126b.png">

**Additional context**
[See storybook composition docs](https://storybook.js.org/docs/react/sharing/storybook-composition#improve-your-storybook-composition) and the use of a build step for npx sb extract to generate the `stories.json` file. That is likely what is missing.

**Comment by duncan-truss** [comment]
I see there is a feature flag as well for `buildStoriesJson` that apparently generates the stories.json https://github.com/storybookjs/storybook/blob/eabc6ef81bbf7ee8d77f5579f94836a7cc1ef3fa/docs/configure/overview.md#feature-flags

**Comment by duncan-truss** [comment]
After the upgrade to Storybook 6.4, I'm not seeing any more errors around a failed network request for stories.json from the https://trussworks.github.io/react-uswds/ URL 🎉 

@haworku Can you check if this is resolved for you as well by the upgrade?  I looked at an old URL you shared for your deployed Storybook and am not seeing any console errors, but not sure if that is the current one you're using.
