### ISSUE TITLE
[fix] Project's example doesn't seem to compile/run

### ISSUE THREAD

**Issue by TomNUSDS** [trussworks/react-uswds#1922]
**ReactUSWDS Version & USWDS Version:**
`Latest` in the package.json

**Describe the bug**
Duplicate the example project and try to build or run it. Seems like the dependencies were updated but there were some backwards compatibility breaking changes related to react?

Seems like I might be doing something wrong? Can I get a sanity check? I was actually try to report a different bug and thought that modifying your example was a good starting point. But it doesn't seem to compile anymore?

**To Reproduce**

1. Duplicate the `https://github.com/trussworks/react-uswds/tree/main/example` folder.
2. In `package.json` change `"@trussworks/react-uswds": "file:./..",` => `"@trussworks/react-uswds": "latest",`
3. Run `yarn` install all required packages
4. Run the package scripts "build"
Result: Fails with:
> ./src/App.tsx
> Attempted import error: 'Switch' is not exported from 'react-router-dom'.

and

>   Property 'activeClassName' does not exist on type 'IntrinsicAttributes & NavLinkProps & RefAttributes<HTMLAnchorElement>'.  TS2322
>
>   36 | 
>   37 |   const navItems = [
>   38 |     <NavLink to={HOME_PAGE} activeClassName="usa-current" exact>   

**Expected behavior**
Should work.

**Device and Browser Information (please complete the following information if describing a UI bug):**

OS: MacOS
Browser: N/A since related to the build process

**Comment by Igarfinkle** [comment]
I'm seeing this same issue. Let me take a look at it! It seems to be an issue where we bumped `react-router-dom` to v6, but didn't make all the necessary changes. I think it'd be a good idea for me to also add a GitHub actions workflow that builds the example app and runs its tests.

**Comment by rpdelaney** [comment]
The example app was removed in #2162

**Comment by rpdelaney** [comment]
The example app was removed in #2162
