### ISSUE TITLE
[fix] Nav dropdown button not closing when clicking outside of it

### ISSUE THREAD

**Issue by werdnanoslen** [trussworks/react-uswds#1930]
**ReactUSWDS Version & USWDS Version:**

ReactUSWDS: 2.8.0
USWDS: 2.13.1

**Describe the bug**

Nav dropdown button doesn't close when clicking outside of it. Instead, it stays open until clicking the button again.

**To Reproduce**

1. Go to the [header storybook](https://trussworks.github.io/react-uswds/?path=/story/components-header--basic-header)
2. Click on a nav dropdown button
3. Click outside the menu/button
4. See that the meny does not close until you click the dropdown button again

![react storybook](https://user-images.githubusercontent.com/764090/159977139-d2f4385d-e816-47f2-9ee4-3cb898353f08.gif)

**Expected behavior**

It [should](https://designsystem.digital.gov/components/header/#basic-header) close upon clicking anywhere else:

![uswds source](https://user-images.githubusercontent.com/764090/159977023-1c65d5de-4bd6-49ad-a21e-36e6af63f8f3.gif)

**Device and Browser Information (please complete the following information if describing a UI bug):**

 - Firefox 98.0.2, Chrome 99.0.4844.83, Safari 15.3
 - Mac 12.2.1

**Comment by brandonlenz** [comment]
I'm taking a look at this right now. Looks like the escape key should also close the menu, however unfocusing the button should not close the menu unless the entire nav is not in focus.

**Comment by Igarfinkle** [comment]
I should note that this behavior is a function of how we've set up the component in storybook. Consumers of React-USWDS can (and in fact, must) create their own handlers for when to open and close the nav. Borrowing from a conversation on Truss Slack, we have the option to

1. Leave it alone. Let consumers of react-uswds set their own open/close togglers. 
2. Use the [uswds-made listener](https://github.com/uswds/uswds/blob/develop/src/js/components/navigation.js)
3. Write our own listener, trying to mirror the behavior of the listener above.

**Comment by werdnanoslen** [comment]
@kmars2022 I've updated the link above, which has since been refactored and can now be found [here](https://github.com/uswds/uswds/blob/29eebc4abe3d9c9d968bd3ef54cff9e8add449eb/packages/usa-header/src/index.js#L81). We have proceeded with option 1, leaving it to consumers to write their own togglers.
