### ISSUE TITLE
[docs] Perform documentation audit + update for implementation guide

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#2015]
**Is your documentation related to a problem or inconsistency? Please describe.**
Following https://github.com/trussworks/react-uswds/issues/2001, it would behoove us to ensure that the documentation for new consumers of the library implementing it for the first time is up-to-date. My recommendation for this issue it to take lessons learned by folks who've experienced implementing the library on a project perform an audit of our existing documentation:

- [Install - README.md](https://github.com/trussworks/react-uswds/blob/main/README.md#install) 
- [Usage - README.md](https://github.com/trussworks/react-uswds/blob/main/README.md#usage)

and make any tweaks necessary. Especially in a scenario where the example app is not present, it is important that documentation in this area is clear and concise.

**Comment by werdnanoslen** [comment]
I'll do a round of checks with Truss projects...

**Comment by brandonlenz** [comment]
I think what this ticket is asking for was accomplished around the time of the [USWDS 3.x upgrade](https://github.com/trussworks/react-uswds/pull/2203), specifically in [this PR](https://github.com/trussworks/react-uswds/pull/2205).

I still struggle with scss and webpack configuration depending on the project framework I'm using (Create React App vs NextJS vs Plain old react + Storybook), but I think that's more me not being an expert with JS build tooling, and not something we can expect this library to give perfect instructions for every permutation for.

I think about this library doing to bundling and exporting of uswds to encapsulate the complexity, but consumers often prefer (and should) choose the uswds scss modules they need to keep their application smaller, so there's little value in us re-engineering the way that USWDS is exported to our consumers from the way I understand it

**Comment by brandonlenz** [comment]
Anyways, I'm okay with closing this issue, but if you're doing a round of checks and find anything I'm sure that will be valuable
