### ISSUE TITLE
[fix] react-uswds no longer ships a .d.ts file, cannot be used with TypeScript any more

### ISSUE THREAD

**Issue by lpsinger** [trussworks/react-uswds#2053]
**ReactUSWDS Version & USWDS Version:**

`@trussworks/react-uswds@3.0.0`, `uswds@2.13.1`

**Describe the bug**

react-uswds 3.0.0 no longer ships a .d.ts file, so it cannot be used in strict TypeScript projects.

**To Reproduce**

See https://github.com/tachgsfc/gcn.nasa.gov/runs/6163692157?check_suite_focus=true. Error message:

```
Error: app/components/CopyableCode.tsx(9,41): error TS7016: Could not find a declaration file for module '@trussworks/react-uswds'. '/home/runner/work/gcn.nasa.gov/gcn.nasa.gov/node_modules/@trussworks/react-uswds/lib/index.js' implicitly has an 'any' type.
[5](https://github.com/tachgsfc/gcn.nasa.gov/runs/6163692157?check_suite_focus=true#step:6:5)
  Try `npm i --save-dev @types/trussworks__react-uswds` if it exists or add a new declaration (.d.ts) file containing `declare module '@trussworks/react-uswds';`
[6](https://github.com/tachgsfc/gcn.nasa.gov/runs/6163692157?check_suite_focus=true#step:6:6)
````

**Expected behavior**

react-uswds should ship an index.d.ts file.

**Screenshots**

**Additional context**

**Device and Browser Information (please complete the following information if describing a UI bug):**

**Comment by Joshua-Flores** [comment]
Experiencing the same issue

**Comment by brandonlenz** [comment]
I'm looking in to this at the moment. Will update as a fixed version becomes available.

@lpsinger For now I would recommend staying on the 2.8.0 release.

**Comment by brandonlenz** [comment]
This will be resolved in the next release. Likely 3.0.2
