### ISSUE TITLE
[feat] Accordion component should support single selectable section behavior by default

### ISSUE THREAD

**Issue by duncan-truss** [trussworks/react-uswds#207]
**Does your feature request relate to a specific USWDS feature?**
This is an enhancement to the existing Accordion component https://designsystem.digital.gov/components/accordion/.  The current implementation defaults to multiselectable behavior where multiple sections can be open at once.  However in the USWDS library the default behavior is expanding one section will collapse all others and multiselectable is opt in.

**Is your feature request related to a problem? Please describe.**
No it is just another component feature of the current spec that someone may want.

**Describe the solution you'd like**
To align with the behavior of USWDS make multiselectable an attribute/prop set to false by default.

**Additional context**

From a Slack conversation, the original implementation was made for a project that only needed the multiselectable behavior

**Comment by SirenaBorracha** [comment]
^^ I accidentally updated the title here and not in my PR
