### ISSUE TITLE
[fix] CircleCI storybook artifact deployment urls no longer work

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#2077]
**Describe the bug**

CircleCI deployment urls no longer point to the CircleCI index.html artifact. This is due to a change that Circle made where they no longer expose artifacts over the URL pattern we previously used.

**To Reproduce**

1. Go to any PR
2. Click on the deployment link posted to the PR as a part of the CI build.
3. Note the "Artifact not found"

**Expected behavior**

The deployment should point to a URL for index.html that circleCI serves.

**Additional context**

A possible solution involves new URL patterns https://support.circleci.com/hc/en-us/articles/5034956515355-How-to-Programmatically-Construct-the-URLs-for-Artifacts

**Comment by rpdelaney** [comment]
CircleCI has been removed as part of #2237
