### ISSUE TITLE
[feat] Determine example app CI / testing workflow

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#208]
**Does your feature request relate to a specific USWDS feature?**
No

**Is your feature request related to a problem? Please describe.**
Based on the work done in https://github.com/trussworks/react-uswds/pull/206 we now have an example app as part of this codebase, but there is no automated testing for it built into our CI.

**Describe the solution you'd like**
What kinds of tests would be helpful to run on the example app as part of the library CI workflow? i.e., end-to-end Cypress? When should they run? i.e., every build, merge to develop, etc?

**Comment by haworku** [comment]
No more example app, no need for this ticket.
