### ISSUE TITLE
Table fullWidth generating class name src-components-Table-Table-module__fullwidth--fOyj6 [fix]

### ISSUE THREAD

**Issue by rmoore-theta** [trussworks/react-uswds#2178]
**ReactUSWDS Version & USWDS Version:**
"@trussworks/react-uswds": "^3.0.2",
"react": "^18.0.0",
"uswds": "^2.13.3",

**Describe the bug**
When using <Table striped bordered fullWidth> it generates the following output 
<table class="usa-table src-components-Table-Table-module__fullwidth--fOyj6 usa-table--striped" data-testid="table">

**To Reproduce**

**Expected behavior**
The expected behavior of fullWidth should be to add the class full-width and that the table would take up the full width of its container on the page

**Screenshots**
![Screen Shot 2022-07-11 at 1 02 04 PM](https://user-images.githubusercontent.com/104368921/178318657-c747cf7f-a9e6-44fd-91a8-194a0fcb851f.png)

**Additional context**
Using fullWidth="true" does not change the behavior. 
No unit test exist for this functionality.

**Device and Browser Information (please complete the following information if describing a UI bug):**

**Comment by sawyerh** [comment]
I believe what's happening is:

- This is currently relying on a [custom CSS rule](https://github.com/trussworks/react-uswds/blob/36caa170a505f8cd8fe0a46537cbd9db0fa36313/src/components/Table/Table.module.css#L0-L3)
- That CSS rule is only included in the `lib/index.css` file, which needs imported as `@import '~@trussworks/react-uswds/lib/index.css';`

So, if a project is only loading the USWDS stylesheets, and not importing the `react-uswds` CSS, the fullwidth styles aren't being loaded on the page, hence now 100% width being applied.

That said, this problem could likely be avoided for at least the `fullWidth` prop by utilizing the USWDS `width-full` utility class: https://github.com/trussworks/react-uswds/pull/2268

**Comment by haworku** [comment]
The fix by @sawyerh has been merged. It will be released soon. Thank you!
