### ISSUE TITLE
[feat] Button refactor

### ISSUE THREAD

**Issue by plummer-flex** [trussworks/react-uswds#218]
**Does your feature request relate to a specific USWDS feature?**
`<Button />`

**Is your feature request related to a problem? Please describe.**
There are two primary issues with this refactor.

1. When utilizing the Button component, the current color/size inline props are unclear and allow for duplication.  
2. The library doesn't include a solution for applying the button styles to anchor nodes.

Example 1, according to props, this would be valid:

```
<Button secondary accent base big small />
```

Example 2, well... it doesn't exist so I don't really have one. :(

**Describe the solution you'd like**
1. Adopt a `color` and `variant` props instead of inlined props.

```
<Button color="secondary" size="small" />
```

2. Add a `link` value to the `type` enum and an optional `url` or `href` prop and programmatically define the rendered root node.

```
<Button type="link" href="http://bin.go">BINGO</Button>

**Describe alternatives you've considered**
At the very least, color and size should be enums.  The case could be made for variant to include inverse or outline, but I don't view this as an immediate concern.

Create a new `<Link />` component or apply the classnames manually.

**Additional context**
This is a standard practice in other UI component libraries. 
https://material-ui.com/components/buttons/
https://react.semantic-ui.com/elements/button/#variations
https://v2.grommet.io/button
https://pinterest.github.io/gestalt/#/Button

**Comment by suzubara** [comment]
See related issues:
- https://github.com/trussworks/react-uswds/issues/187
- https://github.com/trussworks/react-uswds/issues/161

These are 💯  valid concerns, but I believe they are covered by the issues above. I am marking those as high priority.
