### ISSUE TITLE
[fix] when ComboBox options prop is updated displayed options do not change

### ISSUE THREAD

**Issue by yeonsy** [trussworks/react-uswds#2182]
**ReactUSWDS Version & USWDS Version:**

react-uswds: 3.1.0
uswds: 2.13.3

**Describe the bug**

When ComboBox `options` prop is updated displayed options do not change

![gif demonstrating issue](https://raw.githubusercontent.com/yeonsy/bug-report/main/react-uswds/combobox-options-update/demo.gif)

Seems like the component should watch for changes to the prop and dispatch an update options action

**To Reproduce**

See: https://github.com/yeonsy/bug-report/tree/main/react-uswds/combobox-options-update#readme

**Expected behavior**

Displayed options should be synced with `options` prop

**Device and Browser Information (please complete the following information if describing a UI bug):**

Firefox 102

**Comment by fanwari1** [comment]
It has been a while since this was reported. Does anyone have any update on this? Even when you call an api to get data and then call a setter, it still doesn't work. It makes it very difficult to use this component.
