### ISSUE TITLE
Aria-hide lock icon and flag in banner

### ISSUE THREAD

**Issue by werdnanoslen** [trussworks/react-uswds#2185]
The lock icon and surrounding parentheses can be made `aria-hidden`, as it only communicates visual information.
https://github.com/trussworks/react-uswds/blob/c9f71d7d7989fb9c7ab2e264d1af26436dcb66c3/src/components/GovBanner/GovBanner.tsx#L64
<img width="199" alt="image" src="https://user-images.githubusercontent.com/764090/183445750-be5f0008-7a6c-4ac2-b45b-74cb103332c6.png">

Ditto for the flag image, which is purely decorative:
https://github.com/trussworks/react-uswds/blob/c9f71d7d7989fb9c7ab2e264d1af26436dcb66c3/src/components/GovBanner/GovBanner.tsx#L129-L133
<img width="83" alt="image" src="https://user-images.githubusercontent.com/764090/183447208-e16d71d7-a593-4df0-a207-984c8f241804.png">

**Comment by brandonlenz** [comment]
The PR I'm working on will allow consumers to do this if they create a custom banner, but the standard GovBanner that we export for convenience should match the [USWDS component code](https://designsystem.digital.gov/components/banner/), for better or for worse.

For updating the USWDS recommended implementation, I'd recommend [filing a bug with USWDS](https://github.com/uswds/uswds/issues)

**Comment by werdnanoslen** [comment]
ah, will do, you can close this one then

**Comment by werdnanoslen** [comment]
Opened issue here: https://github.com/uswds/uswds/issues/4912

**Comment by werdnanoslen** [comment]
USWDS implemented [this](https://github.com/uswds/uswds/issues/4912)! Can this be closed then or does it need a follow-up issue?
