### ISSUE TITLE
Support for USWDS v3

### ISSUE THREAD

**Issue by kbayliss** [trussworks/react-uswds#2189]
### Discussed in https://github.com/trussworks/react-uswds/discussions/2176

<div type='discussions-op-text'>

<sup>Originally posted by **kbayliss** June 29, 2022</sup>
USWDS v3.0 was released on 28th April 2022, and I was wondering if there are any plans to either change to or support this within this package? Or whether this package will support USWDS v2.0 only. 

https://designsystem.digital.gov/about/releases/
https://designsystem.digital.gov/whats-new/updates/2022/04/28/introducing-uswds-3-0/
</div>

**Comment by rogeruiz** [comment]
Thanks @kbayliss. I'll commented on your Discussion topic that you have linked to at the top of your description. Let's make sure that Issues can be used for tracking implementations within the project. I apologize on behalf of the OSS team for React-USWDS for our delay in giving you a response. Thanks again.
