### ISSUE TITLE
[chore] Upgrade USWDS to v3

### ISSUE THREAD

**Issue by aligg** [trussworks/react-uswds#2199]
**Which USWDS component(s) does this relate to?**
Dependencies

**Code line**
https://github.com/trussworks/react-uswds/blob/e36635f1ad3c7142f4860749e5392157d518e3d4/package.json#L52

**Further detail**
Hi! I wanted to check if we have plans to upgrade to [USWDS v3](https://designsystem.digital.gov/documentation/migration/) so that react-uswds will be v3 compatible? Apologies if there is already an issue for this elsewhere 🙏 and thanks in advance for any deets! Happy to try and take on the upgrade if helpful!

**Comment by aligg** [comment]
@gidjin would you have any objections if I open a PR for this?

**Comment by kbayliss** [comment]
Relevant discussion: https://github.com/trussworks/react-uswds/discussions/2176
