### ISSUE TITLE
[fix] Search component should support default value 

### ISSUE THREAD

**Issue by 1Maria** [trussworks/react-uswds#2206]
**ReactUSWDS Version & USWDS Version:**

**Describe the bug**

Cannot add default value to the search component.

**To Reproduce**

1. Go to Search component story 
2. Add `defaultValue` prop and value
3. View in Storybook

**Expected behavior**

See a default value appear in the search bar 

**Screenshots**

**Additional context**

**Device and Browser Information (please complete the following information if describing a UI bug):**

**Comment by 1Maria** [comment]
I have a PR for this coming

**Comment by haworku** [comment]
Thanks for opening this issue! Left a comment on your PR regarding the use case here. https://github.com/trussworks/react-uswds/pull/2207#issuecomment-1291121366 I wasn't sure if this was the same thing as `placeholder` or something different.
