### ISSUE TITLE
[feat] Update to latest typescript version

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#2213]
**Is your feature request related to a problem? Please describe.**

We need to upgrade to the latest TS version to make sure we're staying up to date

**Describe the solution you'd like**

React USWDS is updated to [newest TS version at time of taking on this item](https://www.npmjs.com/package/typescript?activeTab=versions)

- Any TS compile issues resolved
- Verify that our packaged library contains the TS type definitions
- Test locally with an existing project using ReactUSWDS (point to the TS upgrade branch/sha)

**Additional context**

**Comment by haworku** [comment]
Latest version is now 4.9

**Comment by werdnanoslen** [comment]
By 'latest' does this issue seek to tie our package.json version to the [`latest`](https://www.npmjs.com/package/typescript/v/latest?activeTab=versions) tagged version of TS? Or was this issue back when we just hadn't updated typescript in a while?
