### ISSUE TITLE
[fix] Update Mobile Menu Close Icon

### ISSUE THREAD

**Issue by jhancock532** [trussworks/react-uswds#2214]
**ReactUSWDS Version & USWDS Version:**

This applies to ReactUSWDS 3.2.0 and USWDS 3.2.0.

**Description of Issue:**

The mobile menu close icon is a bold close icon, from an earlier version of USWDS. This should be updated to the new, thin cross icon, from the latest version of USWDS.

**To Reproduce**

1. Go to [the header component in react uswds Storybook](https://trussworks.github.io/react-uswds/?path=/story/components-header--basic-header).
2. Resize the page to mobile width.
3. Click on the Menu button
4. See old icon.
5. Go to [the header component in USWDS component library](https://designsystem.digital.gov/components/header/)
6. Open component in preview mode, and resize page to mobile width.
7. Click on the Menu button.
8. See new icon.

**Expected behavior**

The icons for the React USWDS and USWDS component libraries to be consistent.

**Screenshots**

React USWDS

<img width="901" alt="Screenshot 2022-11-07 at 10 05 01" src="https://user-images.githubusercontent.com/18164832/200283070-48e5f216-0d19-44c3-8147-21c1d6ab4e84.png">

USWDS Component Library

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18164832/200283238-0d8327eb-a3b1-45e9-8742-c86aa5c6bae2.png">

**Device and Browser Information:**

 - OS: MacOS
 - Browser: Chrome
 - Version: 107

**Comment by jhancock532** [comment]
When I installed this library for local development and viewed the Storybook instance, the correct close icon renders. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18164832/200345362-dd456ee8-671a-4aac-b1ba-1f55bca26d43.png">

This issue can be closed - to save confusion, please could we update the storybook instance for this repository so it reflects the current state of the codebase?

**Comment by werdnanoslen** [comment]
Our hosted storybook now also reflects this
