### ISSUE TITLE
[feat] Update to the latest Jest version

### ISSUE THREAD

**Issue by kleinschmidtj** [trussworks/react-uswds#2216]
**Is your feature request related to a problem? Please describe.**

We need to upgrade to the latest Jest version to make sure we're staying up to date. This work should happen before upgrading TypeScript [#2213](https://github.com/trussworks/react-uswds/issues/2213).

**Describe the solution you'd like**

Jest is upgraded to the latest version at the time of taking this issue on.

- Any test issues resolved.
- Upgrade `babel-jest` and `jest` to same versions.

**Comment by werdnanoslen** [comment]
By 'latest' does this issue seek to tie our package.json version to the [`latest`](https://www.npmjs.com/package/jest/v/latest?activeTab=versions) tagged version of Jest? Or was this issue back when we just hadn't updated Jest in a while?
