### ISSUE TITLE
[docs] Update "About" section of repo to reflect USWDS 3.0

### ISSUE THREAD

**Issue by sawyerh** [trussworks/react-uswds#2219]
GitHub description should get updated to USWDS **3** 😄  

<img width="322" alt="CleanShot 2022-11-10 at 16 26 17@2x" src="https://user-images.githubusercontent.com/371943/201233975-e09decdf-8b5a-4fbf-b343-1e2214cf8678.png">

Related: f5bf2e70369f860e6af67305557ff626009c2585

**Comment by brandonlenz** [comment]
This has been updated, thanks for calling it out!
<img width="313" alt="image" src="https://user-images.githubusercontent.com/15805554/204889473-04a3db17-f594-4305-b65b-2eb203320b5c.png">

**Comment by brandonlenz** [comment]
@sawyerh would you like to be added to our all-contributors?

**Comment by sawyerh** [comment]
@brandonlenz sure 😄
