### ISSUE TITLE
[feat] Upgrade to React 18(+)

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#2222]
**Is your feature request related to a problem? Please describe.**

ReactUSWDS needs react 18 support.

**Describe the solution you'd like**

ReactUSWDS is running on React 18+ (latest minor version at the time of implementation)

**Describe alternatives you've considered**

It has to be done eventually 😛. Peer dependency is already set up to help quell some warnings and compatibility for consumers, but we need to use react 18 itself on this library.

**Additional context**

Relates to: 
Jest upgrade may need to happen simultaneously to support deprecated react 17 render methods, (we think): #2216 
Typescript react 18 might require updated typescript types to be compatible. There may be a dependency here #2213

**Comment by rpdelaney** [comment]
Was this fixed in #2197 ? @brandonlenz
