### ISSUE TITLE
[fix] Pagination next/previous button icons missing label

### ISSUE THREAD

**Issue by jlhogan** [trussworks/react-uswds#2229]
**ReactUSWDS Version & USWDS Version:**

ReactUSWDS: 3.2.0
USWDS: 2.13.3

**Describe the bug**

When using the Pagination component, our automated AXE tests throw an error because the included arrow icon svgs have `role="img"` but no associated alt text. See test error:
```
 "<svg> elements with an img role must have an alternative text (svg-img-alt)"

    Fix any of the following:
      Element has no child that is a title
      aria-label attribute does not exist or is empty
      aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
      Element has no title attribute
```

**To Reproduce**
Include the Pagination component and run through automated AXE tests. 

**Expected behavior**

ReactUSWDS is accessible by default and using components as-is does not result in AXE errors.

**Comment by werdnanoslen** [comment]
This SVG is imported from USWDS directly, so please post an issue there to request this edit. While this does result in an automated test error, you'll find in both Voiceover and JAWS that the ARIA label is read and properly accessible.

**Comment by papeshh** [comment]
I recently ran into this issue issue too with the SVG in the pagination component throwing an error in AXE scans.  Looking at the  pagination component in the USWDS library, they consider the caret icon decorative and add aria-hidden to the SVG which prevents it from being flagged by AXE.  Any chance we can reopen this bug ticket and apply the same fix here?
