### ISSUE TITLE
[fix] Remove last remaining CircleCI Job and ensure storybook artifacts are saved in github actions

### ISSUE THREAD

**Issue by gidjin** [trussworks/react-uswds#2237]
Truss discourages the use of CircleCI for our projects as noted [in our Engineering Playbook](https://playbook.truss.dev/docs/infrasec/ci_cd#platform). This project has one job using CircleCI and the rest using GitHub Actions, which is also an anti-pattern.

So this issue is to remove the one remaining cirlce ci job and ensure that the storybook artifacts are saved by the `deploy-storybook.yml` GitHub workflow. Our decision to move from CircleCI to Github actions should also be documented in an ADR.

AC:
- Removal of `.circleci/config.yml`
- Delete our data on circleci for the project, if any is needed
- Add support to save static storybook output in github workflow action `.github/workflows/deploy-storybook.yml`
- Add an ADR describing our choice to use GitHub actions
- Update any links in our Readme or project pointing to circleci

References:
- This would replace / close #2077 in my opinion.

**Comment by rpdelaney** [comment]
I believe the AC are completed _except_ we still need the ADR and documentation updates.

**Comment by haworku** [comment]
Made a new issue for docs only. Marking this as done
