### ISSUE TITLE
[fix] lib/index.css includes all USWDS styles, but should it?

### ISSUE THREAD

**Issue by sawyerh** [trussworks/react-uswds#2270]
**ReactUSWDS Version:** 4.1.1

**Describe the bug**

I think there's a bug, confusing documentation, or potentially both.

In the README's usage section it says:

> Also make sure to include the following in order to import the compiled CSS from this project:
> `@import '~@trussworks/react-uswds/lib/index.css';`
>If you aren't already using USWDS as a dependency, **you also need to import USWDS styles**.

In the [Styles and Assets doc](https://github.com/trussworks/react-uswds/blob/main/docs/styles_and_assets.md), it says:

> If you already have uswds as a dependency (this is most likely already the case) you only need `import '@trussworks/react-uswds/lib/index.css'` in your application.

I interpret all of the above to say:

1. Projects still need to import the `@uswds/uswds` package's CSS (or Sass)
2. `react-uswds` also has a CSS file with **additional** styles, which projects should also import.

What I'm observing however is that the `~@trussworks/react-uswds/lib/index.css` includes USWDS styles, not just additional styles.

**To Reproduce**

1. Run `yarn build` in this repo
1. Look at `lib/index.css`

**Expected behavior**

If I'm understanding correctly, I _think_ what's supposed to be happening is:

1. `index.css` includes any custom styles that are in this repo, but does not include any from the USWDS package itself
2. `uswds.css` includes the USWDS styles

**Screenshots**

Example of a USWDS style in the `index.css` file, but from what I can tell, this is only coming from USWDS:

<img width="1237" alt="CleanShot 2023-02-25 at 14 13 27@2x" src="https://user-images.githubusercontent.com/371943/221381925-e76f2237-044b-45ec-bfc0-83936753ab73.png">

<img width="300" alt="CleanShot 2023-02-25 at 14 16 54@2x" src="https://user-images.githubusercontent.com/371943/221382020-ec49d9db-61c7-40c8-a033-3492ec1bd186.png">

**Comment by haworku** [comment]
I agree this is strange. I'm going to look into this. I will comment here what I find and when (if) this changed. 

Going in, this is my interpretation was my understanding also 
   > Projects still need to import the @uswds/uswds package's CSS (or Sass)
  >  react-uswds also has a CSS file with additional styles, which projects should also import.
