### ISSUE TITLE
[fix] Husky pre-commit checks no longer working after migration

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#2280]
**Describe the bug**

A recent (for us) major version change for Husky introduced "breaking" changes, which manifsted for ReactUSWDS by silently stopping to perform the checks that we were performing. We need to fix the husky checks, or replace them.

Previously, husky allowed them to be configured in the package.json:

```
  "husky": {
    "hooks": {
      "pre-commit": "tsc && lint-staged",
      "pre-push": "yarn danger local -b main --failOnErrors"
    }
  },
```

**To Reproduce**

1. Make a commit on a new branch
2. Notice pre-commit checks do not run
3. Push up
4. Notice pre-push checks do not run

**Expected behavior**

We need to re-evaluate the purpose of these checks as a part of our developer flow and CI. A 1:1 replacement for what we were doing is okay, but is it the right choice?

For example, project's I've been on have made the argument that the `tsc` typescript compile check should be done in CI at the PR level, because sometimes it is valuable to make in-progress commits (especially for larger refactors) that do no resolve all tsc issues at once.

I recommend investing some decision energy on what we'd like to do going forward, while the slate is "clean" so to speak. This also represents an opportunity to re-evaluate the tooling used, e.g. the [Husky](https://github.com/typicode/husky) vs [pre-commit](https://pre-commit.com/) vs other discussion

**Comment by werdnanoslen** [comment]
would also love for prettier `format:fix` to be added as well
