### ISSUE TITLE
[feat] Support internationalization and customization of the File Input's instructions

### ISSUE THREAD

**Issue by sawyerh** [trussworks/react-uswds#2399]
**Does your feature request relate to a specific USWDS component?**

[FileInput](https://trussworks.github.io/react-uswds/?path=/story/components-file-input--single-file-input)

**Is your feature request related to a problem? Please describe.**

The `FileInput` includes instructions saying "Drag file here or choose from folder". [This English string is hard-coded into the component code](https://github.com/trussworks/react-uswds/blob/5761db6e66db98c8299efb978bbe39fd259f1209/src/components/forms/FileInput/FileInput.tsx#L191-L194), which prevents translating it into other strings and prevents customizing it to account for user feedback indicating the phrasing is confusing on touch devices. 

**Describe the solution you'd like**

Support passing in an alternative instruction via a prop. For example:

```tsx
<FileInput
    instruction="Select or drop files here"
```

**Additional context**

This is essentially a copy of these two upstream USWDS issues, however since `react-uswds` replicates this functionality, I think y'all are in a position to address it via React props.

https://github.com/uswds/uswds/issues/3445
https://github.com/uswds/uswds/issues/3567

**Comment by werdnanoslen** [comment]
@haworku I think most applications would have the whole page change language, which I think is what the [Language selector component](https://designsystem.digital.gov/components/language-selector/#accessibility) should do. For specific parts of a page changing language (e.g. if a spanish language page has a small amount of English), then [WCAG agrees](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#accessibility) with you in using the lang prop on that component's level
