### ISSUE TITLE
[fix] Alert component body to use a tag that allows more HTML tags

### ISSUE THREAD

**Issue by vim-usds** [trussworks/react-uswds#2502]
**ReactUSWDS Version & USWDS Version:**
- "@trussworks/react-uswds": "^5.0.0",
-  "@uswds/uswds": "^3.5.0",

**Describe the bug**
The Alert component uses a `<p>` tag as the body and limiting what tags can be specified as children. 

**To Reproduce**

1. Go to Alert component
2. Inspect the HTML
3. See that it's a p

**Expected behavior**
If the body was a `<div>` for instance, it would allow for more HTML tags as children (ie, bullets).

**Comment by werdnanoslen** [comment]
For precedent, USWDS uses an alert component with a list in the body in their Validation component: https://designsystem.digital.gov/components/validation/

**Comment by werdnanoslen** [comment]
oh nice, then maybe this issue could be scoped to just adding a story to the storybook covering that prop?

**Comment by kleinschmidtj** [comment]
Yeah, that's a good idea. That would make the use of the prop more visible.
