### ISSUE TITLE
[feat] Upgrade @uswds/uswds to current version 3.5

### ISSUE THREAD

**Issue by kleinschmidtj** [trussworks/react-uswds#2503]
**Does your feature request relate to a specific USWDS component?**

[Many packages within USWDS](https://github.com/uswds/uswds/releases/tag/v3.5.0). We are currently on 3.1.

**What USWDS Version is this feature present in?**

3.5

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Upgrade the dependency from 3.1 to 3.5. Either directly or first [resolve the dependabot PR.](https://github.com/trussworks/react-uswds/pull/2305)

**Describe alternatives you've considered**

**Additional context**

**Comment by werdnanoslen** [comment]
All work to get us there are labelled with https://github.com/trussworks/react-uswds/labels/uswds%20update

**Comment by werdnanoslen** [comment]
This is a blocker to merging our current https://github.com/trussworks/react-uswds/labels/uswds%20update to v3.5 work, which depends on style mostly in v3.3.
