### ISSUE TITLE
[feat] Add missing icons to react-uswds

### ISSUE THREAD

**Issue by kleinschmidtj** [trussworks/react-uswds#2506]
**Does your feature request relate to a specific USWDS component?**

Yes, the [Icon](https://designsystem.digital.gov/components/icon/)

**What USWDS Version is this feature present in?**

Various, but 3.1.0 is an example. That release introduced a linkedin icon.

**Missing in react-uswds from usa-icons:**

- linkedin.svg
- edit.svg
- fax.svg (😄 )
- remove_circle.svg

**Is your feature request related to a problem? Please describe.**

react-uswds does not have all the icons from USWDS

**Describe the solution you'd like**

Update the code to use all icons. Update storybook to show them.

**Comment by werdnanoslen** [comment]
FYI edit was already in there, just not in the storybook
