### ISSUE TITLE
[feat] Improve storybook display for mobile components 

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#253]
**Is your feature request related to a problem? Please describe.**
The user must resize the browser manually or use dev tools to properly view responsive components. This causes confusion because it looks like mobile components are broken when loaded on a larger screen.

**Describe the solution you'd like**
Display components in different sizes and layouts with the [Viewport](https://github.com/storybookjs/storybook/tree/master/addons/viewport) addon. 

Viewport is Storybook's official addon - it includes a device dropdown and can be configured by component or by story. We should implement this in `<Footer />` stories as a starting place.

**Describe alternatives you've considered**
- [Taffy](https://github.com/DEGJS/storybook-addon-taffy) addon 
- [Responsive Views](https://github.com/vizeat/storybook-addon-responsive-views) addon 

**Additional context**
This is how the Mobile Footer story looks when loaded on a larger screen.
![Screen Shot 2020-06-15 at 9 58 56 AM](https://user-images.githubusercontent.com/10750442/84673146-e83d4380-aeee-11ea-9cc6-6377eee4db61.png)

**Comment by duncan-truss** [comment]
Closing this issue because it was completed and released in 1.9.0 https://github.com/trussworks/react-uswds/pull/387
