### ISSUE TITLE
[fix] react-uswds does not work in esm projects

### ISSUE THREAD

**Issue by lpsinger** [trussworks/react-uswds#2542]
**ReactUSWDS Version & USWDS Version:**

\@trussworks/react-uswds\@5.1.1, `@uswds/uswds`@3.1.0

**Describe the bug**

This package only works in CommonJS projects, not ESM ones. I am observing this bug when using \@trussworks/react-uswds with the [Remix](https://remix.run) framework.

**To Reproduce**
I have created a minimal reproducer at https://github.com/lpsinger/react-uswds-bug-report-esm/tree/esm using the [create-remix](https://www.npmjs.com/package/create-remix) template.

1.  Clone the repo, install, and start the dev server:

        git clone https://github.com/lpsinger/react-uswds-bug-report-esm
        cd react-uswds-bug-report-esm
        npm i
        npm run dev

2.   Open a web browser and point it at http://localhost:3333.

**Expected behavior**
You should see a page with a USWDS Button labeled "Hello, world".

**Screenshots**
![Screenshot 2023-08-03 at 12 38 44](https://github.com/trussworks/react-uswds/assets/728407/a62976e5-1642-4e63-8447-69436061a997)

**Additional context**
This works fine if you change the server module format to ESM. To see it working:

1.  Interrupt or kill the dev server (on Linux or macOS, type Control-C).
2.  Nuke everything, switch branches, re-install, and re-run the dev server:

    git checkout --track origin/cjs
    git clean -dxf
    npm i
    npm run dev

Then refresh the browser window. You should now see the following:

![Screenshot 2023-08-03 at 12 43 09](https://github.com/trussworks/react-uswds/assets/728407/aaca668c-a6a1-4d47-9b4b-fb47d5fa58e6)

**Device and Browser Information (please complete the following information if describing a UI bug):**

 - OS: macOS
 - Browser: Safari
 - Version: 16.6 (18615.3.12.11.2)

**Comment by werdnanoslen** [comment]
I believe this should work in our next release. Can you confirm by pulling the main branch directly from `trussworks/react-uswds` into your project?

**Comment by lpsinger** [comment]
Yes, it works now. Thank you!
