### ISSUE TITLE
Replace Card's Buttons with Links

### ISSUE THREAD

**Issue by werdnanoslen** [trussworks/react-uswds#2696]
**Which USWDS component(s) does this relate to?**
Card

**What USWDS Version was this component introduced by?**
3.5.0 (missed in #2682)

**Describe the bug**
Replace `Button`s with `Link`s using the`usa-button` class, and be sure spacebar activation works, per https://github.com/uswds/uswds/pull/4385

**Code snippet**

Before:

```
<Card>
  ...
  <CardFooter>
    <Button type="button" secondary>
      Stick out
    </Button>
  </CardFooter>
</Card>
```

After:

```
<Card>
  ...
  <CardFooter>
    <Link href={"#"} className="usa-button">
      Stick out
    </Link>
  </CardFooter>
</Card>
```

**Further detail**

https://trussworks.github.io/react-uswds/?path=/docs/components-typography-link--default#styled-as-button

**Comment by werdnanoslen** [comment]
> May I take up this issue?

Absolutely @devesh-2002, thanks!

**Comment by devesh-2002** [comment]
I just replaced the Buttons with Links (on Card) , but to me it seems like the spacebar activation is not working. Am I going wrong anywhere?
https://drive.google.com/file/d/1tDZbH295XVppYluXaijjJ2_kMZsuWUoY/view?usp=sharing

**Comment by werdnanoslen** [comment]
@devesh-2002 can you please make a PR and I'll take a look at it? You'll need to implement [this function](https://github.com/uswds/uswds/blob/develop/packages/usa-button/src/index.js#L6-L17), as space doesn't activate links by default.
