### ISSUE TITLE
[feat] Consistently `export` component props (CheckboxProps, etc) so they can be easily overridden

### ISSUE THREAD

**Issue by TomNUSDS** [trussworks/react-uswds#2778]
**Does your feature request relate to a specific USWDS component?**

Some input elements have their props exported allowing them to be easily wrapped and customized, but some others do not. It's inconsistent and requires work-arounds like [this from nasa.gov](https://github.com/nasa-gcn/gcn.nasa.gov/blob/fa5dab7d17c49a1ef14c4f3e110d64ed330ee238/app/components/nested-checkboxes/NestedCheckboxes.tsx#L14) and [this one from trussworks](https://github.com/trussworks/unemployment-insurance-modernization-demo/blob/131d9d9d6423f464302ad7f23834247a8cb5457c/src/components/form/fields/CheckboxGroupField/CheckboxGroupField.tsx#L17) and [this one from dept of labor](https://github.com/USDepartmentofLabor/ui-claimant-experience-pilot/blob/5a89ed619dfcd54da84d5e28e040d9f31e1c9ded/claimant/src/components/form/fields/CheckboxGroupField/CheckboxGroupField.tsx#L14)

Examples of exported props:

- [TextInputProps](https://github.com/trussworks/react-uswds/blob/b5fb85d0ec17c1a02b1d4c2e373d2204342aac38/src/components/forms/TextInput/TextInput.tsx#L29)
- [TextareaProps](https://github.com/trussworks/react-uswds/blob/b5fb85d0ec17c1a02b1d4c2e373d2204342aac38/src/components/forms/Textarea/Textarea.tsx#L12)

Examples of non-exported props:

- [CheckboxProps](https://github.com/trussworks/react-uswds/blob/b5fb85d0ec17c1a02b1d4c2e373d2204342aac38/src/components/forms/Checkbox/Checkbox.tsx#L4)
- [ComboBoxProps](https://github.com/trussworks/react-uswds/blob/b5fb85d0ec17c1a02b1d4c2e373d2204342aac38/src/components/forms/ComboBox/ComboBox.tsx#L43C6-L43C19)
- [RadioProps](https://github.com/trussworks/react-uswds/blob/b5fb85d0ec17c1a02b1d4c2e373d2204342aac38/src/components/forms/Radio/Radio.tsx#L4)

**What USWDS Version is this feature present in?**

6.2.0

**Is your feature request related to a problem? Please describe.**

Searching github shows lots of different work-around for something that could be solved by simply as adding an `export` keyword to your library.

**Describe the solution you'd like**

Add `export` to common component props?

**Describe alternatives you've considered**

I'm seeing various work-around in open source github repos like:

```typescript
checkboxProps?: Omit<ComponentProps<typeof CheckboxField>, OptionOmitProps>;`
```

and

```typescript
type CheckboxArgs = Parameters<typeof Checkbox>
type CheckboxProps = CheckboxArgs[0]
```

**Additional context**

While there are work-arounds, they are more complex and probably shouldn't be required.

**Comment by werdnanoslen** [comment]
Hi Tom, this is something we've [been looking into](https://github.com/trussworks/react-uswds/issues/2587), and there is [a draft PR](https://github.com/trussworks/react-uswds/pull/2728) that addresses this. If there is anything you'd add to those two, can you comment there please, and we can close this as a duplicate?

**Comment by TomNUSDS** [comment]
Sorry for the duplicate request. I thought I searched before opening it.

Thanks again for your continued work on this project!
