### ISSUE TITLE
[docs] Not possible to see the React code of stories

### ISSUE THREAD

**Issue by sawyerh** [trussworks/react-uswds#2786]
It's not currently possible, when viewing Storybook, to see the source code for a Story. This makes it difficult for developers to know how to use a component in a similar way. For example, the custom tooltip:

![CleanShot 2024-02-29 at 10 09 27@2x](https://github.com/trussworks/react-uswds/assets/371943/0e869d33-c86a-4a10-a05e-6c74e5043902)

A potential solution would be to add this addon: https://storybook.js.org/addons/@storybook/addon-storysource

**Comment by werdnanoslen** [comment]
Hi there, yes, unfortunately we didn't notice this when we updated storybook, so I have [another PR](https://github.com/trussworks/react-uswds/pull/2795) to bring that back
