### ISSUE TITLE
[feat] Add sizeVariant and Validation enum props to TextComponent

### ISSUE THREAD

**Issue by ahobson** [trussworks/react-uswds#283]
**Does your feature request relate to a specific USWDS feature?**
[Form Control component](https://designsystem.digital.gov/components/form-controls/) specifically the `TextInput` subcomponent

**Is your feature request related to a problem? Please describe.**
Discussion of problem is in #187.

**Describe the solution you'd like**
* Add new `sizeVariant ` prop.
* Deprecate `small`, `medium` props in favor of new `sizeVariant` prop.
* Add new `validationStatus` prop.
* Deprecate `error`, and `success` props in favor of new `validationStatus` prop.
* Add new tests and adjust stories as needed.

This work should look very similar to #229.

**Describe alternatives you've considered**
n/a, we converged on a solution for handling these cases in the linked issue.

**Comment by suzubara** [comment]
minor naming suggestion:
- `inputWidth` instead of `sizeVariant`? that might make it a _little_ clearer what dimension is being sized here (I had to go back to Storybook and remind myself we're talking about the width of the input element, not something like the text size for example)
