### ISSUE TITLE
[feat] Automate release tags

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#326]
**Does your feature request relate to a specific USWDS feature?**
No, this is related to dev flow and releasing

**Is your feature request related to a problem? Please describe.**
Creating a release in GH, adding a tag that matches our new `package.json` version, and adding release notes matching our changelog is a manual step we could avoid.  

**Describe the solution you'd like**
Whenever a release PR is merged to `main` automate: 
-  add tag with the number from `package.json` version. 
- add release notes in GH.  

Here are some github actions to test out:
- [Create Release](https://github.com/actions/create-release) **
- [Githug Tag Action](https://github.com/anothrNick/github-tag-action) 
- [GitHub Create Tag Release](https://github.com/marketplace/actions/github-create-tag-release) 

**Describe alternatives you've considered**
- Allow  `standard-version` to add tags locally. Then,  instead of only publishing to npm locally after a merge, we could also push up tags - ` git push --follow-tags origin main && npm publish` 
- Just use [`semantic-release`](https://github.com/semantic-release). This was the tool we wanted to use in #118.  Would still like to see us use this tool. I think [the reason we held off was to be cautious](https://github.com/trussworks/react-uswds/pull/141) which is probably good since we changed our dev flow a few times since then.  

Once there is a way to `npm publish` in CI while meeting infra requirements  (with mfa) - we should probably reach for `semantic-release` instead of `standard-version`.

**Comment by brandonlenz** [comment]
@haworku release-please actually does this for us now, so I believe this can be closed! (It creates the tag when the release branch is merged, e.g. https://github.com/trussworks/react-uswds/pull/2601#issuecomment-1741263708)
