### ISSUE TITLE
Upgrade to Node v14 - 10/2020

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#344]
On 2020-10-12, Node 14 should be in active LTS, which means it should be safe for us to update this library to use Node 14 for development. 

Ensure all dependencies support and function in v14 without issues. You can do this by checking the releases for all dependencies, updating to the latest stable versions, changing the `.node-version`, adjusting engines in `package.json`, then making sure all tests and builds pass in this project.

Once verified everything looks good, the new Node version should also be specified in:
    `docs/contributing.md`
    `.circleci/config.yml`
  `.github/deploy-storybook.yml`

**Comment by derekkinsman** [comment]
Hi, I was wondering if there has been any movement on this issue now that Node 14 is in LTS? Cheers.
