### ISSUE TITLE
[bug] [ci] Danger hung up on "Pending"

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#357]
**Describe the bug**
Danger randomly gets hung on a pending state - _"Expected, waiting for status to be reported"_. This prevents merge since we require this action the pass.  The issue can be resolved by rerunning the entire ci workflow, but that shouldn't be necessary. 

**To Reproduce**
1. Open a PR and see it get hung up
2. circle ci console looks like this
```
yarn danger ci --failOnErrors

yarn run v1.22.4
$ /home/circleci/react-uswds/node_modules/.bin/danger ci --failOnErrors
Skipping Danger due to this run not executing on a PR."
Done in 0.35s.

CircleCI received exit code 0
```
2. Rerunning the worflow resolves the issue and things work the second time

**Expected behavior**
Want danger to run and complete the first time 😅

**Comment by ahobson** [comment]
I tried enabling debug logging in #358 but it worked the first time

**Comment by ahobson** [comment]
I closed my PR and then made a new branch and pushed it up.  There wasn't a PR associated with it, but the pipeline in CircleCI still started.  I intentionally didn't create the PR right away.

The [results in CircleCI](https://app.circleci.com/pipelines/github/trussworks/react-uswds/1371/workflows/7143346a-2ec2-495c-92df-2731073eecb4/jobs/1387/parallel-runs/0/steps/0-108) show that the danger checks were skipped.

I think this is the most likely explanation: when PRs are opened after the CI run finishes, they don't have danger results.

I'm not sure there's a good way to fix this.

**Comment by haworku** [comment]
@ahobson the thing that makes me 🤔 is the fact this issue happened on all the dependabot PRs this week too. But maybe something is different about the way the Github dependabot does things now. This was never happening before.

**Comment by ahobson** [comment]
The [danger code says](https://github.com/danger/danger-js/blob/master/source/ci_source/providers/Circle.ts#L7) we should enable "Only Build pull requests".  We do *not* have that set in Circle right now.  I'm inclined to turn that on.

**Comment by ahobson** [comment]
The "only build pull requests" setting was enabled in CircleCI on 3 August

**Comment by ahobson** [comment]
We haven't had any problems since enabling the setting in CircleCI, so I'm closing this issue
