### ISSUE TITLE
[docs] Cleanup docs for new contributors

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#377]
We have started getting outside pull requests 🎉 . This is great and let's clean up things a bit.

- Separate the releasing guide from contributing guide.
- Improve contributing guide to more clearly highlight how external PRs will be merged (currently we have to replicate work to a new branch for CI runs, eventually we have automation for this). 
- Double check accuracy, readability of contributing guide and PR template in general.

**Comment by jim** [comment]
We could move the checklist part of the PR template into a section (instead of a comment at the beginning) so that the list is visible in PRs by default. I think showing it at the beginning in a comment can be confusing- what are we expecting folks to do with it?
