### ISSUE TITLE
[fix] Skip Happo runs on dependabot PRs again

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#450]
**Describe the bug**
Somewhere in the last month or so Happo stopped skipping for dependabot PRS. This was likely when dependabot switched over to being a Github tool. 

Currently, Dependabot is getting is blocked up from automerging regularly by Happo-  requiring someone to go in and manually accept the change. 

 The way we fixed this last time was by adjusting circleci config - specifically adding this condition command ` '[[ ( "${CIRCLE_PR_USERNAME}" != "dependabot" ) && ( "${CIRCLE_PR_USERNAME}" != "dependabot-preview" ) ]] && yarn happo-ci'`. That is no longer working.  

**To Reproduce**
- See any open dependabot PR that has happo failures. They happen weekly on Mondays.

**Comment by haworku** [comment]
Reopening because that didn't work.  Need to look around more what's going on or try this as GH actions which has a clear way it handles bots.

**Comment by haworku** [comment]
Let's also also consider removing storybook from automated dependency upgrades  (this would be a change to `dependabot.yml`) since that could change the happo output.

**Comment by ahobson** [comment]
I notice looking at the CI build step "Preparing environment variables" that `CIRCLE_USERNAME` is empty for dependabot PRs but it's set for PRs from people.  I think that means you can do `[[ -n "${CIRCLE_PR_USERNAME}" ]] && yarn happo-ci`

**Comment by haworku** [comment]
@ahobson oh thanks!!! I was just reading a github issue where people talking about the PR username being empty in some cases.

**Comment by ahobson** [comment]
I gave bad advice.  `[[ -n "${GITHUB_USERNAME}" ]] && yarn happo-ci` exits with a status of 1 if `GITHUB_USERNAME` is unset.
