### ISSUE TITLE
[feat] Update GovBanner to include HTTPS section

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#456]
**Does your feature request relate to a specific USWDS feature?**
This issue is about improving our `GovBanner` component to match improvements to USWDS [Banner ](https://designsystem.digital.gov/components/banner/). The 2.8.0 release [made changes to the Banner](https://designsystem.digital.gov/whats-new/updates/2020/09/08/Improvements-banner/) that still need to be reflected in our library

**Describe the solution you'd like**
- Add HTTP section to `GovBanner`
- Update the default English text our in Storybook examples (`GovBanner.stories.tsx`) to match the new default text.
- Make any other changes to Storybook that make our example more in sync with [the USWDS implementation](https://designsystem.digital.gov/components/banner/)

**Comment by MissyM2** [comment]
Hi, there,  I would like to work on this issue.  Please let me know!

**Comment by MissyM2** [comment]
Hi, there, again. @haworku I was interested in working on this issue as well as the step issue.  I haven't heard anything so I thought I would reach out again.  Let me know!

**Comment by haworku** [comment]
@MissyM2 Excuse me, I missed the ping in comments and just saw this now. For the future if you would like to open a PR or a WIP branch at any time we welcome it. We are quick to respond to PRs and comments there.  Will check whats going on with my notifications for comments 😕
