### ISSUE TITLE
Upgrade to Node v12

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#72]
As of 2019-10-21, Node 12 is in active LTS, which means it should be safe for us to update this library to use Node 12 for development.

First, ensure that all dependencies support and function in v12 without issues. You can do this by checking the releases for all dependencies, updating to the latest stable versions, and making sure all tests and builds pass in this project.

Once verified everything looks good, the new Node version should be specified in:
- `package.json`
- `docs/contributing.md`
- `.circleci/config.yml`

**Comment by haworku** [comment]
I believe managing node versions with `nvm` is preferred. It also what is on the Node.js site.  Let's update our `contributing.md` docs to use nvm instead of brew as well as part of this work.

**Comment by gidjin** [comment]
The other option is to use docker to control what version of node is used when people develop for the project. I have a branch that I started where I added a dockerfile, let me know if you want me to bring it back or if decided to go that route. ` gdjn_docker_setup`

**Comment by suzubara** [comment]
I'm a fan of `nvm` but I've also heard some talk about it not being the preferred way to install node at Truss. I don't remember why.

I've never seen a JS library be opinionated about what dev environment someone should use for contributing though. It would make sense to have a dockerfile if this were an application but since it's an OS package I think we should try to stay relatively unbiased, and just be clear about requirements (ie, must be using this version of node/yarn) vs. recommendations (brew, nvm, docker, etc.). That's my 2c.

**Comment by sojeri** [comment]
Since this is a library and not an application, I think we should follow the common JS library pattern of mentioning at the top of the README details like minimum required node version and which version(s) we prefer for development.

IMO if folks need more guidance about installing different node versions, we should link to node's guidance or to something in the Truss eng playbook if we want to enforce our own opinions.

**Comment by tinyels** [comment]
The issue with `nvm` was that installing it with homebrew isn't supported by the maintainers. On MilMove we have a convention of installing all of our prereqs with `brew` and that would have been an issue for that. It looks like we could use `nodenv`  instead and avoid this.  `nodenv` can automatically select the appropriate node version for a given project which would be really nice for people working in multiple projects.

**Comment by haworku** [comment]
@tinyels ah thanks  -that's helpful context about milmove.  I've been v confused about all the `brew` references.  

@suzubara  sounds good.  I saw the `contributing.md` right now suggests installing by `brew` this is why I brought it up. I thought I was sharing a good practice but apparently its just an inherited opinion. 😄
