### ISSUE TITLE
New Component: Identifier

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#737]
# [Identifier](https://designsystem.digital.gov/components/identifier/)

## Description
The identifier communicates a site’s parent agency and displays agency links required by federal laws and policies.
![Screen Shot 2020-12-28 at 2 14 16 PM](https://user-images.githubusercontent.com/10750442/103240814-fa288600-4916-11eb-80e8-3bb46a15d86e.png)

## Requirements (proposed)
**Prop Interface**
``` 
Props = { }  & JSX.IntrinsicElements['div']
```

**Sample Implementation**
```javascript
 return (
      <div className="usa-identifier">
       {children}
      </div>) 
```

```JSX
<Identifier>
  <IdentifierMasthead />
  <IdentifierLinks / >
  <IdentifierGov>
 </Identifier>
```
**More Details**
  -   `<div>`root element
  -  IdentifierMasthead and IdentifierGov components have `section` root element, IdentifierLinks is `nav`

## Other Considerations
-  "With rare exceptions, if you use the identifier, include the entire identifier. That is, don't delete sections or required links or change any link text beyond the customizations mentioned in the implementation section."
- "Use the identifier component for required links. If your site already includes the federally required links in its site footer, remove them in favor of the links in the identifier."

**Comment by suzubara** [comment]
Fixed by https://github.com/trussworks/react-uswds/pull/1044
