### ISSUE TITLE
Set up test coverage collection

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#75]
Keep track of code test coverage in this repo. Since we're open source we can probably use a free service!

**Comment by haworku** [comment]
Potential scope:
- [ ] add a yarn script test coverage that runs `jest --coverage` 
- [ ] add github badges that show code coverage

Or what does a  "test coverage collection" mean? Maybe I'm misunderstanding.

**Comment by eamahanna** [comment]
@suzubara @haworku I would like to look into this further. Is there a particular direction either of you were imagining?

**Comment by suzubara** [comment]
@jenniferlynparsons tagging you in case you have any thoughts or preferred tools? Since we're open source anything that is free for open source and will integrate easily with CircleCI or Github Actions would be ideal

**Comment by jenniferlynparsons** [comment]
I wish I had preferred tools to offer! Previous projects I've worked on had a precommit hook that was set for 100% coverage so that made it simple. 😄  
That said, this tool looks interesting and robust and offers a completely free tier for open source projects. https://about.codecov.io/

**Comment by suzubara** [comment]
To clarify the scope of this issue:
- Minimum requirement is that some part of the CI flow fails if test coverage drops below a certain threshold. I think we can define that threshold to wherever it is now, and use it to ensure we aren't dropping.
- A nice to have would be a badge displaying current code coverage info in the README, but this will likely require integrating with a service like codecov.io and IMO is not strictly necessary as part of this issue.
