### ISSUE TITLE
[dependencies] Upgrade to webpack 5

### ISSUE THREAD

**Issue by haworku** [trussworks/react-uswds#768]
Dependabot could not automatically merge webpack but [there is a new major version](https://webpack.js.org/blog/2020-10-10-webpack-5-release/) and eventually, when its more mature, we should evolve.  Until then,  this is an issue to reference as we close any lingering dependabot merges related to webpack utilities.

**Comment by haworku** [comment]
Looks like storybook doesn’t yet officially support webpack 5 
https://github.com/storybookjs/storybook/issues/9216

**Comment by suzubara** [comment]
This is happening as part of https://github.com/trussworks/react-uswds/pull/1544
