### ISSUE TITLE
[feat] Deprecate the Modal component (breaking)

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#787]
**Does your feature request relate to a specific USWDS component?**
No

**Is your feature request related to a problem? Please describe.**
See https://github.com/trussworks/react-uswds/issues/786

**Describe the solution you'd like**
Remove the Modal component from this library entirely, pending decision to start a new Truss UI library where it can be relocated.

**Comment by brandonlenz** [comment]
Merged into V2 in https://github.com/trussworks/react-uswds/pull/956

**Comment by brandonlenz** [comment]
Reopening because we still need to safely migrate the Modal component to a Truss specific library

**Comment by haworku** [comment]
After more discussion, the need for migrating the previous Modal component to a Truss library is no longer needed. We can proceed on building the new Modal
