### ISSUE TITLE
[feat] Tile display variant of checkbox

### ISSUE THREAD

**Issue by jenniferlynparsons** [trussworks/react-uswds#790]
# [Bordered Checkbox](https://designsystem.digital.gov/components/form-controls/#checkbox)

## USWDS Version

Version 2.10.0

## Description
We currently have a checkbox component, but 2.10.0 introduced a bordered version of the checkbox which we have implemented ad-hoc on MilMove.

## Example Implementation (proposed)
Should be an additional variations of existing Checkbox component

**Comment by suzubara** [comment]
Modifying this issue type to [feat] since it is a variant of an existing component, rather than a brand new one. Requirements are similar to https://github.com/trussworks/react-uswds/issues/166
