### ISSUE TITLE
USWDS Component: Range slider

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#81]
Add Range slider component: https://designsystem.digital.gov/components/form-controls/#range

**Comment by haworku** [comment]
Suggested scope:
- [ ] New component should be added to the existing `Form` folder
- [ ] Props must handle HTML [range input ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range )behaviors. This include `min`, `max`, `step`and the input `value`.  Will also need to be able to call an event handler on change to update parent.
- [ ] Both keyboard interaction or click to drag should move the slider
- [ ] As per uswds docs,  "set the `step` attribute so it’s not too granular"
- [ ] As per uswds docs, provide a way for optional labels to be added to the beginning and end of slider to describe the min and max values.
