### ISSUE TITLE
[fix] Wrapping Breadcrumb variant does not wrap on Safari

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#869]
**ReactUSWDS Version & USWDS Version:**

ReactUSWDS: 1.11.0
USWDS: 2.8.0+

**Describe the bug**

The [Wrapping `Breadcrumb` component variant](https://trussworks.github.io/react-uswds/?path=/story/components-breadcrumb--wrapping-breadcrumb) does not wrap in safari, though the [USWDS example](https://designsystem.digital.gov/components/breadcrumb/) _does_.

**To Reproduce**

1. Go to https://trussworks.github.io/react-uswds/?path=/story/components-breadcrumb--wrapping-breadcrumb using Safari
2. Adjust viewport size smaller until the breadcrumbs should wrap
3. Note that the breadcrumbs do not wrap

**Expected behavior**

For all browsers, the wrapping `Breadcrumb` variant should wrap

**Screenshots**

Safari:
![image](https://user-images.githubusercontent.com/15805554/107414170-a1d0d080-6adf-11eb-8b0f-3f84d2cb94c5.png)

Chrome:
![image](https://user-images.githubusercontent.com/15805554/107414187-aac1a200-6adf-11eb-94be-ac2aa667a7bf.png)

**Additional context**

**Device and Browser Information (please complete the following information if describing a UI bug):**

 - Browser: First found in Safari on MacOS
 - Safari Version  14.0.3

**Comment by brandonlenz** [comment]
I've spent considerable time today trying to debug this issue. It's really strange. 

#### Things I've tried so far:
- Compare rendered html for wrapping breadcrumb within storybook vs. uswds html (Appear to be identical)
- Compare assigned and computed styles for wrapping breadcrumb within storybook vs uswds (Appear to be identical)
- Investigate storybook parent containers to see if they are altering the behavior of the wrapping breadcrumb (as far as I can tell this is not happening).
- Update to uswds 2.10.0 in case I missed a styling difference in my test above which may have been the result of a uswds fix for this exact issue (still does not wrap in storybook)
- Repeat all the above testing with new storybook example returning the raw html directly from uswds example code (does not wrap in storybook)
- Import Breadcrumb into a test CRA. This is to rule out storybook shenanigans. (Does not wrap in test app either):
![image](https://user-images.githubusercontent.com/15805554/107568277-c480e900-6bb4-11eb-8a35-476c45b2c94d.png)

I'm wondering if there is a specific property on a parent component in the uswds example that enforces the wrapping there. I'm going to try a test App next using just the pure uswds styles and raw html to see if wrapping works there. If not, I'll open an issue with uswds.

**Comment by brandonlenz** [comment]
uswds v2.10.1 will include a fix for this at the css class-level: https://github.com/uswds/uswds/pull/4004/files

@haworku @suzubara this will effectively be automatically resolved for us once we reach parity with uswds. I added this to the uswds 2.10.0 milestone (technically this is 2.10.1, not 2.10.0 though). Does that sound appropriate? Should I leave this issue open until that time?

**Comment by haworku** [comment]
@brandonlenz This sounds like quite a thing to debug. Thanks for sticking with it and filing the issue. 

Adding this issue to the 2.10.0 milestone makes sense to me (I think anything under 2.10.x could go under there). 

I would close the this issue since there's not an independent code change needed  Maybe we need a "won't fix" or "uswds bug" label?

**Comment by brandonlenz** [comment]
Closing per @haworku's recommendation with `uswds bug` label. Will be resolved on reach parity with uswds 2.10.1
