### ISSUE TITLE
Add HTML example stories

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#87]
It is probably worth documenting base USWDS styles that apply to just plain old HTML, without creating React components for them. For example, what does a `ul, ol, dl` look like with the USWDS CSS applied? We should add Storybook stories to illustrate these elements.

For a comprehensive list of HTML elements, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element

**Comment by plummer-flex** [comment]
> It is probably worth documenting base USWDS styles that apply to just plain old HTML, without creating React components for them. For example, what does a `ul, ol, dl` look like with the USWDS CSS applied? We should add Storybook stories to illustrate these elements.
> 
> For a comprehensive list of HTML elements, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element



> It is probably worth documenting base USWDS styles that apply to just plain old HTML, without creating React components for them. For example, what does a `ul, ol, dl` look like with the USWDS CSS applied? We should add Storybook stories to illustrate these elements.
> 
> For a comprehensive list of HTML elements, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element

The original USWDS documentation does this already. 

https://designsystem.digital.gov/components/

Does this statisfy your proposed need? If not, help me understand the benefit of including HTML examples in this React library.

**Comment by haworku** [comment]
Late here but @plummer-flex point makes sense to me.  Our goal for the storybook is to provide examples of using our React component -  rather than replicating the main USWDS design documentation which will always be more up to date.  Closing this issue.
