### ISSUE TITLE
[fix] Latest release (1.12.0) cannot be installed

### ISSUE THREAD

**Issue by andrewkfiedler** [trussworks/react-uswds#923]
**ReactUSWDS Version & USWDS Version: 1.12.0**

```
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @trussworks/react-uswds@1.12.0 postinstall: `husky install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @trussworks/react-uswds@1.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrewfiedler/.npm/_logs/2021-02-19T19_20_24_777Z-debug.log
```

**To Reproduce**
1.  Attempt to install 1.12.0 on a project, note the failure above

**Expected behavior**

Installs without errors

**Screenshots**
![Screen Shot 2021-02-19 at 12 30 39 PM](https://user-images.githubusercontent.com/11984853/108552273-50c69680-72ae-11eb-946c-92cd7a85c673.png)

**Additional context**

Rolling back to version 1.11.0 works

**Comment by brandonlenz** [comment]
@andrewkfiedler thanks for reporting this! We'll have a fix available for this in our next release (likely Monday)!

(reopening for now. I will close this manually on release so that you will know when the fix is available).

**Comment by brandonlenz** [comment]
@andrewkfiedler release 1.12.1 is now live! Thanks again, and please let us know if you encounter any other difficulties.

Closing this issue now that the release is live.
