### ISSUE TITLE
Security PR rotation logistics

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#97]
Start a conversation and determine logistics for how we want to handle a security rotation. This function should support:
- Team members from Truss can opt-in to be part of the "on call" rotation
- On-call shifts should have a pre-determined length of time
- Add description of responsibilities while on-call -- primarily paying attention to any security alerts that come in from Github, making sure urgent PRs are being attended to, etc. The on-call person may not be required to resolve issues themselves, but instead make sure they are not being dropped or ignored.

**Comment by suzubara** [comment]
After reading this doc I have some new thoughts: https://help.github.com/en/github/managing-security-vulnerabilities/about-security-alerts-for-vulnerable-dependencies

It _sounds_ like when GH finds dependency vulnerabilities, it should also be opening a PR automatically to update the dependencies in question, via Dependabot. So once we have Dependabot auto-merging fixed, that will hopefully take care of the majority of the work to address security issues. However there may be cases where this automated flow does not resolve security alerts:
- If the alert originates in a nested dependency and the direct dependency hasn't yet released a fix
- If the alert originates in our own code (oh no)

So I think it still makes sense to have some kind of rotation where there's someone responsible for noticing these issues and shepherding them forward. But since this role ideally won't have a lot to do most of the time, I wonder if we can also add regular housekeeping responsibilities such as making sure there aren't any stalled PRs/releases, issues or conversations created by someone outside of Truss, etc. To be clear, this person isn't responsible for _fixing_ any of the above, but rather should just be on top poking whoever can fix them and making sure threads don't get dropped.

I'd love to hear any feedback or thoughts anyone has!

**Comment by haworku** [comment]
I like this idea.  If there are few security issues during a rotation,  it gives that person  clear ways to contribute to overall maintenance.    I don't think this should be too much of a lift.
