### ISSUE TITLE
Dependabot can't automerge PRs

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#98]
Try making dependabot a code owner of yarn.lock to see if that unblocks its automerge process

**Comment by suzubara** [comment]
I did some investigating, and I don't think that adding Dependabot as a CODEOWNER will resolve this issue. Instead, we could add this Github action and configure it to auto-approve PRs opened by the Dependabot user: https://github.com/marketplace/actions/auto-approve

Also see thread here: https://github.com/dependabot/feedback/issues/86

If this sounds like a reasonable solution I'll go ahead and implement, but I wanted to get an initial 👍 / 👎 first!

@tinyels @gidjin @esacteksab

**Comment by esacteksab** [comment]
It does sound like a reasonable solution to me. Thanks for running this down! I can't remember if @eeeady solved this problem in other repos where we use Dependabot. Perhaps they have a solution or recommendation. If not, perhaps this is the solution to the Terraform modules that Dependabot maintains for us.
