### ISSUE TITLE
Add docs about running yarn audit as part of a PR

### ISSUE THREAD

**Issue by suzubara** [trussworks/react-uswds#99]
Update docs on how to add an audit to a PR that changes dependencies

**Comment by sojeri** [comment]
JFYI re: timing-- I am not planning to grab this until next week (Monday).

**Comment by suzubara** [comment]
👍 I think this was mentioned in the original conversation but I forgot to include in the issue desc - it might also be worth seeing if we can enforce this using https://danger.systems/js/ (we already have a dangerfile setup)
