### ISSUE TITLE
New Component: Icon

### ISSUE THREAD

**Issue by brandonlenz** [trussworks/react-uswds#992]
> :warning: **Note**: Creating this issue as a new "component" because it is listed by uswds as a component, _however_ there are many decisions to make around adding support internally and externally for the uswds icons. I'm going to compile some notes regarding my thoughts here, but before beginning work on this, I would suggest distilling via some discussion. The most important step in beginning this work will be to import uswds 2.10.0+ and see exactly how the icons are exposed to us, and how we can best wrap them. I don't _know_ that an Icon component is the way to go with this, but it seems like it could be good for us to use internally, and also expose for external use.

# [Icons](https://designsystem.digital.gov/components/icons/)

## USWDS Version

Icons have existed in USWDS previously to 2.10.0, but 2.10.0 added better default support and a broader selection of icons.

Not also that the icons have changed from fontawesome (also see not about docs in Other Considerations):
> **Active icons are found in** dist/img/usa-icons. The icons in this directory will be packaged into an SVG sprite. The complete set of available icons are located in two directories: dist/img/material-icons and dist/img/uswds-icons. Copy icons into a usa-icons directory within your project images directory and rebuild the SVG sprite using uswds-gulp.

## Description
Icons help communicate meaning, actions, status, or feedback.

## Requirements (proposed)
Implementation will largely depend on how the icons are externally exposed, and what importing them looks like. Below is an example thought

**Prop Interface**

```JSX
Props = {
  name: string // See bonus note below about this
  size?: 3 | 4 | 5 | 6 | 7 | 8 | 9 // Default `undefined` (scale to font size). Side note: Typescript ranges please https://github.com/Microsoft/TypeScript/issues/15480 
} & JSX.IntrinsicElements['svg']
```

## Example Implementation (proposed)

The `name` prop should be used to determine the icon path. Icon names match the filename in the [uswds source code](https://github.com/uswds/uswds/tree/develop/src/img/usa-icons). By inserting `name` into the import url for the icon, we can allow the user to select an icon without needing to know anything about the path or internal implementation, so long as they use the correct name from the list of [uswds icons](https://designsystem.digital.gov/components/icons/#all-icons). Just be sure that a name that does not match an existing icon errors acceptably.

```JSX
<Icon name="accessibility_new" size={6} />
```

> ### Bonus: 
> As mentioned above, while `name` is a `string` it would be nice to also have type safety (and IDE autocomplete) where only strings matching actual icon names are allowed. 
>
> If uswds icons in 2.10.0 are exported statically in a format that we can accomplish this with, I think that would be worth pursuing.
> 
> I recommend discussion and using personal judgement here.

**More Details**

- `<svg>`root element
- Default class `usa-icon`
- 

## Other Considerations

- ~~There are several places in the code where we use uswds icons. GovBanner uses a lock icon for example. As a part of this effort, it would be a good idea to evaluate replacing our icons internally with the icon component (especially wherever we may still be using font-awesome).~~
- ~~In our [styles and assets documentation](https://github.com/trussworks/react-uswds/blob/main/docs/styles_and_assets.md) we're recommending using fontawesome per uswds' recommendation (which no longer appears to be there, in favor of their internal list of icons). Our documentation surrounding Icons should be updated alongside this PR~~
- ~~USWDS examples set some intrinsic props to defaults (e.g. `focusable` and `role`). We should set the same defaults, but allow override if the corresponding prop is passed to the `Icon` component~~

Updated some of these other considerations to be a part of their own Issue: https://github.com/trussworks/react-uswds/issues/1303

**Comment by maya** [comment]
Not explicitly stated in this issue, but USWDS transitioned to using Google Material Icons. When I was looking at your [storybook components](https://trussworks.github.io/react-uswds/), I noticed they still used the FA icons and was wondering when you'd update it.

**Comment by brandonlenz** [comment]
Hey @maya! Thanks for the feedback! 

I updated the issue to be a bit less vague. 

As far as timing goes, we're currently wrapping up reaching parity with USWDS 2.9.0, and beginning work on the 2.10.0 changes, so this issue is just about ready to be started. Be on the lookout for updates soon! As an open-source project we're also happy to help support contributors that want to give it a go before we can get to it internally!
